/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.ceshi.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.Block;

import net.mcreator.ceshi.block.*;
import net.mcreator.ceshi.PrimogemcraftMod;

public class PrimogemcraftModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(PrimogemcraftMod.MODID);
	public static final DeferredBlock<Block> YUANSHIKUANGSHI;
	public static final DeferredBlock<Block> YISHIJIEYUANMUMUBAN;
	public static final DeferredBlock<Block> JIUCHANZHIYUANKUAI;
	public static final DeferredBlock<Block> MOLADUI_02;
	public static final DeferredBlock<Block> MOLAKUAI_01;
	public static final DeferredBlock<Block> YIYISHIJIEMUBANLOUQI;
	public static final DeferredBlock<Block> YIYISHIJIEYUANMUBANZHUAN;
	public static final DeferredBlock<Block> YIYISHIJIEMUZHALAN;
	public static final DeferredBlock<Block> YISHIJIEMUZHALAN;
	public static final DeferredBlock<Block> SANYUEQIDIAOXIANG_01;
	public static final DeferredBlock<Block> JINGZHIMOLAKUAI;
	public static final DeferredBlock<Block> LLIANJIAMOLAKUAI;
	public static final DeferredBlock<Block> LIANJIAMOLAKUAIBANKUAI;
	public static final DeferredBlock<Block> LLIANJIAMOLAKUIAITAIJIE;
	public static final DeferredBlock<Block> LLIANJIAMOLAKUAIQIANG;
	public static final DeferredBlock<Block> XIAOGUANZI;
	public static final DeferredBlock<Block> DAGUANZI;
	public static final DeferredBlock<Block> LAJITONG;
	public static final DeferredBlock<Block> GANJINGLAJITONGXIANGZI;
	public static final DeferredBlock<Block> MMOLAZHILAJITONG;
	public static final DeferredBlock<Block> ZIYOUSONGSHIKUANGSHI;
	public static final DeferredBlock<Block> ZIYOUSONGSHIKUAI;
	public static final DeferredBlock<Block> JIANLAOKUANGSHI;
	public static final DeferredBlock<Block> JIANLAOHUANGYUKUAI;
	public static final DeferredBlock<Block> ZUISHENGKUANGSHI;
	public static final DeferredBlock<Block> ZUISNEGZIJINGKUAI;
	public static final DeferredBlock<Block> SHENGZHANGKUANGSHI;
	public static final DeferredBlock<Block> SHENGZHANGBIFEIDAKUAI;
	public static final DeferredBlock<Block> CAOYUANHEKUAI;
	public static final DeferredBlock<Block> CAOYUANHEHUAMUBAN;
	public static final DeferredBlock<Block> CAOYUANHEHUABUBAN_2;
	public static final DeferredBlock<Block> CCAOYUANHEHUAMUBAN_3;
	public static final DeferredBlock<Block> CESHI_MUCAIBAO_STAIRS;
	public static final DeferredBlock<Block> CESHI_MUCAIBAO_SLAB;
	public static final DeferredBlock<Block> CESHI_MUCAIBAO_FENCE;
	public static final DeferredBlock<Block> CESHI_MUCAIBAO_FENCE_GATE;
	public static final DeferredBlock<Block> CESHI_MUCAIBAO_PRESSURE_PLATE;
	public static final DeferredBlock<Block> CESHI_MUCAIBAO_BUTTON;
	public static final DeferredBlock<Block> CAOMULOUTI_21;
	public static final DeferredBlock<Block> CAOMU_22;
	public static final DeferredBlock<Block> CAOMO_23;
	public static final DeferredBlock<Block> CAOMU_24;
	public static final DeferredBlock<Block> CAOMU_25;
	public static final DeferredBlock<Block> CAOMU_26;
	public static final DeferredBlock<Block> CAOMU_31;
	public static final DeferredBlock<Block> CAOMU_32;
	public static final DeferredBlock<Block> CAOMU_33;
	public static final DeferredBlock<Block> CAOMU_34;
	public static final DeferredBlock<Block> CAOMU_35;
	public static final DeferredBlock<Block> CAOMU_36;
	public static final DeferredBlock<Block> DIJINGQINJINGKUANGSHI;
	public static final DeferredBlock<Block> DIJINGQINGJINKUAI;
	public static final DeferredBlock<Block> LIANJIAXIAJIEHEJINKUAI;
	public static final DeferredBlock<Block> RANYUANMANAOKUANGSHI;
	public static final DeferredBlock<Block> RANYUANKUAI_2;
	public static final DeferredBlock<Block> MUTANKUAI;
	public static final DeferredBlock<Block> XIJAIEYANGENGDI;
	public static final DeferredBlock<Block> AIXUBINGYUKUANGSHI;
	public static final DeferredBlock<Block> AIXUBINGYUFANGKU_I;
	public static final DeferredBlock<Block> YUANSUJINGSHIKUAI;
	public static final DeferredBlock<Block> CESHIXIAODENGFASHEQI;
	public static final DeferredBlock<Block> CHUANGZAOXIAODENGFASHEQI;
	public static final DeferredBlock<Block> YISHIJIEMUBAN_PLANKS;
	public static final DeferredBlock<Block> YISHIJIEMUBAN_STAIRS;
	public static final DeferredBlock<Block> YISHIJIEMUBAN_SLAB;
	public static final DeferredBlock<Block> YISHIJIEMUBAN_FENCE;
	public static final DeferredBlock<Block> YISHIJIEMUBAN_FENCE_GATE;
	public static final DeferredBlock<Block> YISHIJIEMUBAN_PRESSURE_PLATE;
	public static final DeferredBlock<Block> YISHIJIEMUBAN_BUTTON;
	public static final DeferredBlock<Block> D_11;
	public static final DeferredBlock<Block> D_12;
	public static final DeferredBlock<Block> D_13;
	public static final DeferredBlock<Block> D_14;
	public static final DeferredBlock<Block> D_15;
	public static final DeferredBlock<Block> D_16;
	public static final DeferredBlock<Block> D_17;
	public static final DeferredBlock<Block> DISUIKUAI_1;
	public static final DeferredBlock<Block> DISUISHUIJINGTI;
	public static final DeferredBlock<Block> CANGSANGSHIZHUAN;
	public static final DeferredBlock<Block> XIUTIEKUAI;
	public static final DeferredBlock<Block> CSHIXIUTIEZHALAN;
	public static final DeferredBlock<Block> XIUMU;
	public static final DeferredBlock<Block> XIUXIUMULOUQI;
	public static final DeferredBlock<Block> XIUMUZHALAN;
	public static final DeferredBlock<Block> CANGSANGSHIZHUANLOUTI;
	public static final DeferredBlock<Block> CANGSANGSHIZHUANTAIJIE;
	public static final DeferredBlock<Block> CANGSANGSHIZHUANWEIQIANG;
	public static final DeferredBlock<Block> SHIZUOYUANSHIKUAI;
	public static final DeferredBlock<Block> SHENBANYANYUANSHIKUANGSHI;
	public static final DeferredBlock<Block> SHENBANJIANLAOHUANGYUKUANGSHI;
	public static final DeferredBlock<Block> CAOYUANSUECI;
	public static final DeferredBlock<Block> MLXDML_01;
	public static final DeferredBlock<Block> MLXDML_02;
	public static final DeferredBlock<Block> MLXDML_03;
	public static final DeferredBlock<Block> DBMLK;
	public static final DeferredBlock<Block> ZZJSK;
	public static final DeferredBlock<Block> JLJSK;
	public static final DeferredBlock<Block> YHJSK;
	public static final DeferredBlock<Block> ZHJSK;
	public static final DeferredBlock<Block> ZYJSK;
	public static final DeferredBlock<Block> RYJSK;
	public static final DeferredBlock<Block> LAJSK;
	public static final DeferredBlock<Block> DANGAOLIYUE;
	public static final DeferredBlock<Block> XJHPYHFH;
	public static final DeferredBlock<Block> JDYK;
	public static final DeferredBlock<Block> BWDXJHPYHFH;
	public static final DeferredBlock<Block> JIANSHIJINGBAN;
	public static final DeferredBlock<Block> HUALIDUANZAO;
	public static final DeferredBlock<Block> HHZD_0;
	public static final DeferredBlock<Block> HHZD_1;
	public static final DeferredBlock<Block> SHENMIWANOU;
	public static final DeferredBlock<Block> HHZDBOO;
	public static final DeferredBlock<Block> HHYINBAOQI;
	public static final DeferredBlock<Block> YSJTSJ_0;
	public static final DeferredBlock<Block> YSJTSJ_1;
	public static final DeferredBlock<Block> BAITIEKUANGSHI_0;
	public static final DeferredBlock<Block> BAITIEKUANGSHI_1;
	public static final DeferredBlock<Block> YSJSHUIJING_0;
	public static final DeferredBlock<Block> YSJSHUIJING_1;
	public static final DeferredBlock<Block> YSJSHUIJINGCU;
	public static final DeferredBlock<Block> CBTK;
	public static final DeferredBlock<Block> QIYU;
	public static final DeferredBlock<Block> XYDX;
	public static final DeferredBlock<Block> MLXZ;
	public static final DeferredBlock<Block> YSX;
	public static final DeferredBlock<Block> HYX;
	public static final DeferredBlock<Block> QXZHQ;
	static {
		YUANSHIKUANGSHI = REGISTRY.register("yuanshikuangshi", YuanshikuangshiBlock::new);
		YISHIJIEYUANMUMUBAN = REGISTRY.register("yishijieyuanmumuban", YishijieyuanmumubanBlock::new);
		JIUCHANZHIYUANKUAI = REGISTRY.register("jiuchanzhiyuankuai", JiuchanzhiyuankuaiBlock::new);
		MOLADUI_02 = REGISTRY.register("moladui_02", Moladui02Block::new);
		MOLAKUAI_01 = REGISTRY.register("molakuai_01", Molakuai01Block::new);
		YIYISHIJIEMUBANLOUQI = REGISTRY.register("yiyishijiemubanlouqi", YiyishijiemubanlouqiBlock::new);
		YIYISHIJIEYUANMUBANZHUAN = REGISTRY.register("yiyishijieyuanmubanzhuan", YiyishijieyuanmubanzhuanBlock::new);
		YIYISHIJIEMUZHALAN = REGISTRY.register("yiyishijiemuzhalan", YiyishijiemuzhalanBlock::new);
		YISHIJIEMUZHALAN = REGISTRY.register("yishijiemuzhalan", YishijiemuzhalanBlock::new);
		SANYUEQIDIAOXIANG_01 = REGISTRY.register("sanyueqidiaoxiang_01", Sanyueqidiaoxiang01Block::new);
		JINGZHIMOLAKUAI = REGISTRY.register("jingzhimolakuai", JingzhimolakuaiBlock::new);
		LLIANJIAMOLAKUAI = REGISTRY.register("llianjiamolakuai", LlianjiamolakuaiBlock::new);
		LIANJIAMOLAKUAIBANKUAI = REGISTRY.register("lianjiamolakuaibankuai", LianjiamolakuaibankuaiBlock::new);
		LLIANJIAMOLAKUIAITAIJIE = REGISTRY.register("llianjiamolakuiaitaijie", LlianjiamolakuiaitaijieBlock::new);
		LLIANJIAMOLAKUAIQIANG = REGISTRY.register("llianjiamolakuaiqiang", LlianjiamolakuaiqiangBlock::new);
		XIAOGUANZI = REGISTRY.register("xiaoguanzi", XiaoguanziBlock::new);
		DAGUANZI = REGISTRY.register("daguanzi", DaguanziBlock::new);
		LAJITONG = REGISTRY.register("lajitong", LajitongBlock::new);
		GANJINGLAJITONGXIANGZI = REGISTRY.register("ganjinglajitongxiangzi", GanjinglajitongxiangziBlock::new);
		MMOLAZHILAJITONG = REGISTRY.register("mmolazhilajitong", MmolazhilajitongBlock::new);
		ZIYOUSONGSHIKUANGSHI = REGISTRY.register("ziyousongshikuangshi", ZiyousongshikuangshiBlock::new);
		ZIYOUSONGSHIKUAI = REGISTRY.register("ziyousongshikuai", ZiyousongshikuaiBlock::new);
		JIANLAOKUANGSHI = REGISTRY.register("jianlaokuangshi", JianlaokuangshiBlock::new);
		JIANLAOHUANGYUKUAI = REGISTRY.register("jianlaohuangyukuai", JianlaohuangyukuaiBlock::new);
		ZUISHENGKUANGSHI = REGISTRY.register("zuishengkuangshi", ZuishengkuangshiBlock::new);
		ZUISNEGZIJINGKUAI = REGISTRY.register("zuisnegzijingkuai", ZuisnegzijingkuaiBlock::new);
		SHENGZHANGKUANGSHI = REGISTRY.register("shengzhangkuangshi", ShengzhangkuangshiBlock::new);
		SHENGZHANGBIFEIDAKUAI = REGISTRY.register("shengzhangbifeidakuai", ShengzhangbifeidakuaiBlock::new);
		CAOYUANHEKUAI = REGISTRY.register("caoyuanhekuai", CaoyuanhekuaiBlock::new);
		CAOYUANHEHUAMUBAN = REGISTRY.register("caoyuanhehuamuban", CaoyuanhehuamubanBlock::new);
		CAOYUANHEHUABUBAN_2 = REGISTRY.register("caoyuanhehuabuban_2", Caoyuanhehuabuban2Block::new);
		CCAOYUANHEHUAMUBAN_3 = REGISTRY.register("ccaoyuanhehuamuban_3", Ccaoyuanhehuamuban3Block::new);
		CESHI_MUCAIBAO_STAIRS = REGISTRY.register("ceshi_mucaibao_stairs", Ceshi_mucaibaoStairsBlock::new);
		CESHI_MUCAIBAO_SLAB = REGISTRY.register("ceshi_mucaibao_slab", Ceshi_mucaibaoSlabBlock::new);
		CESHI_MUCAIBAO_FENCE = REGISTRY.register("ceshi_mucaibao_fence", Ceshi_mucaibaoFenceBlock::new);
		CESHI_MUCAIBAO_FENCE_GATE = REGISTRY.register("ceshi_mucaibao_fence_gate", Ceshi_mucaibaoFenceGateBlock::new);
		CESHI_MUCAIBAO_PRESSURE_PLATE = REGISTRY.register("ceshi_mucaibao_pressure_plate", Ceshi_mucaibaoPressurePlateBlock::new);
		CESHI_MUCAIBAO_BUTTON = REGISTRY.register("ceshi_mucaibao_button", Ceshi_mucaibaoButtonBlock::new);
		CAOMULOUTI_21 = REGISTRY.register("caomulouti_21", Caomulouti21Block::new);
		CAOMU_22 = REGISTRY.register("caomu_22", Caomu22Block::new);
		CAOMO_23 = REGISTRY.register("caomo_23", Caomo23Block::new);
		CAOMU_24 = REGISTRY.register("caomu_24", Caomu24Block::new);
		CAOMU_25 = REGISTRY.register("caomu_25", Caomu25Block::new);
		CAOMU_26 = REGISTRY.register("caomu_26", Caomu26Block::new);
		CAOMU_31 = REGISTRY.register("caomu_31", Caomu31Block::new);
		CAOMU_32 = REGISTRY.register("caomu_32", Caomu32Block::new);
		CAOMU_33 = REGISTRY.register("caomu_33", Caomu33Block::new);
		CAOMU_34 = REGISTRY.register("caomu_34", Caomu34Block::new);
		CAOMU_35 = REGISTRY.register("caomu_35", Caomu35Block::new);
		CAOMU_36 = REGISTRY.register("caomu_36", Caomu36Block::new);
		DIJINGQINJINGKUANGSHI = REGISTRY.register("dijingqinjingkuangshi", DijingqinjingkuangshiBlock::new);
		DIJINGQINGJINKUAI = REGISTRY.register("dijingqingjinkuai", DijingqingjinkuaiBlock::new);
		LIANJIAXIAJIEHEJINKUAI = REGISTRY.register("lianjiaxiajiehejinkuai", LianjiaxiajiehejinkuaiBlock::new);
		RANYUANMANAOKUANGSHI = REGISTRY.register("ranyuanmanaokuangshi", RanyuanmanaokuangshiBlock::new);
		RANYUANKUAI_2 = REGISTRY.register("ranyuankuai_2", Ranyuankuai2Block::new);
		MUTANKUAI = REGISTRY.register("mutankuai", MutankuaiBlock::new);
		XIJAIEYANGENGDI = REGISTRY.register("xijaieyangengdi", XijaieyangengdiBlock::new);
		AIXUBINGYUKUANGSHI = REGISTRY.register("aixubingyukuangshi", AixubingyukuangshiBlock::new);
		AIXUBINGYUFANGKU_I = REGISTRY.register("aixubingyufangku_i", AixubingyufangkuIBlock::new);
		YUANSUJINGSHIKUAI = REGISTRY.register("yuansujingshikuai", YuansujingshikuaiBlock::new);
		CESHIXIAODENGFASHEQI = REGISTRY.register("ceshixiaodengfasheqi", CeshixiaodengfasheqiBlock::new);
		CHUANGZAOXIAODENGFASHEQI = REGISTRY.register("chuangzaoxiaodengfasheqi", ChuangzaoxiaodengfasheqiBlock::new);
		YISHIJIEMUBAN_PLANKS = REGISTRY.register("yishijiemuban_planks", YishijiemubanPlanksBlock::new);
		YISHIJIEMUBAN_STAIRS = REGISTRY.register("yishijiemuban_stairs", YishijiemubanStairsBlock::new);
		YISHIJIEMUBAN_SLAB = REGISTRY.register("yishijiemuban_slab", YishijiemubanSlabBlock::new);
		YISHIJIEMUBAN_FENCE = REGISTRY.register("yishijiemuban_fence", YishijiemubanFenceBlock::new);
		YISHIJIEMUBAN_FENCE_GATE = REGISTRY.register("yishijiemuban_fence_gate", YishijiemubanFenceGateBlock::new);
		YISHIJIEMUBAN_PRESSURE_PLATE = REGISTRY.register("yishijiemuban_pressure_plate", YishijiemubanPressurePlateBlock::new);
		YISHIJIEMUBAN_BUTTON = REGISTRY.register("yishijiemuban_button", YishijiemubanButtonBlock::new);
		D_11 = REGISTRY.register("d_11", D11Block::new);
		D_12 = REGISTRY.register("d_12", D12Block::new);
		D_13 = REGISTRY.register("d_13", D13Block::new);
		D_14 = REGISTRY.register("d_14", D14Block::new);
		D_15 = REGISTRY.register("d_15", D15Block::new);
		D_16 = REGISTRY.register("d_16", D16Block::new);
		D_17 = REGISTRY.register("d_17", D17Block::new);
		DISUIKUAI_1 = REGISTRY.register("disuikuai_1", Disuikuai1Block::new);
		DISUISHUIJINGTI = REGISTRY.register("disuishuijingti", DisuishuijingtiBlock::new);
		CANGSANGSHIZHUAN = REGISTRY.register("cangsangshizhuan", CangsangshizhuanBlock::new);
		XIUTIEKUAI = REGISTRY.register("xiutiekuai", XiutiekuaiBlock::new);
		CSHIXIUTIEZHALAN = REGISTRY.register("cshixiutiezhalan", CshixiutiezhalanBlock::new);
		XIUMU = REGISTRY.register("xiumu", XiumuBlock::new);
		XIUXIUMULOUQI = REGISTRY.register("xiuxiumulouqi", XiuxiumulouqiBlock::new);
		XIUMUZHALAN = REGISTRY.register("xiumuzhalan", XiumuzhalanBlock::new);
		CANGSANGSHIZHUANLOUTI = REGISTRY.register("cangsangshizhuanlouti", CangsangshizhuanloutiBlock::new);
		CANGSANGSHIZHUANTAIJIE = REGISTRY.register("cangsangshizhuantaijie", CangsangshizhuantaijieBlock::new);
		CANGSANGSHIZHUANWEIQIANG = REGISTRY.register("cangsangshizhuanweiqiang", CangsangshizhuanweiqiangBlock::new);
		SHIZUOYUANSHIKUAI = REGISTRY.register("shizuoyuanshikuai", ShizuoyuanshikuaiBlock::new);
		SHENBANYANYUANSHIKUANGSHI = REGISTRY.register("shenbanyanyuanshikuangshi", ShenbanyanyuanshikuangshiBlock::new);
		SHENBANJIANLAOHUANGYUKUANGSHI = REGISTRY.register("shenbanjianlaohuangyukuangshi", ShenbanjianlaohuangyukuangshiBlock::new);
		CAOYUANSUECI = REGISTRY.register("caoyuansueci", CaoyuansueciBlock::new);
		MLXDML_01 = REGISTRY.register("mlxdml_01", Mlxdml01Block::new);
		MLXDML_02 = REGISTRY.register("mlxdml_02", Mlxdml02Block::new);
		MLXDML_03 = REGISTRY.register("mlxdml_03", Mlxdml03Block::new);
		DBMLK = REGISTRY.register("dbmlk", DbmlkBlock::new);
		ZZJSK = REGISTRY.register("zzjsk", ZzjskBlock::new);
		JLJSK = REGISTRY.register("jljsk", JljskBlock::new);
		YHJSK = REGISTRY.register("yhjsk", YhjskBlock::new);
		ZHJSK = REGISTRY.register("zhjsk", ZhjskBlock::new);
		ZYJSK = REGISTRY.register("zyjsk", ZyjskBlock::new);
		RYJSK = REGISTRY.register("ryjsk", RyjskBlock::new);
		LAJSK = REGISTRY.register("lajsk", LajskBlock::new);
		DANGAOLIYUE = REGISTRY.register("dangaoliyue", DangaoliyueBlock::new);
		XJHPYHFH = REGISTRY.register("xjhpyhfh", XjhpyhfhBlock::new);
		JDYK = REGISTRY.register("jdyk", JdykBlock::new);
		BWDXJHPYHFH = REGISTRY.register("bwdxjhpyhfh", BwdxjhpyhfhBlock::new);
		JIANSHIJINGBAN = REGISTRY.register("jianshijingban", JianshijingbanBlock::new);
		HUALIDUANZAO = REGISTRY.register("hualiduanzao", HualiduanzaoBlock::new);
		HHZD_0 = REGISTRY.register("hhzd_0", Hhzd0Block::new);
		HHZD_1 = REGISTRY.register("hhzd_1", Hhzd1Block::new);
		SHENMIWANOU = REGISTRY.register("shenmiwanou", ShenmiwanouBlock::new);
		HHZDBOO = REGISTRY.register("hhzdboo", HhzdbooBlock::new);
		HHYINBAOQI = REGISTRY.register("hhyinbaoqi", HhyinbaoqiBlock::new);
		YSJTSJ_0 = REGISTRY.register("ysjtsj_0", Ysjtsj0Block::new);
		YSJTSJ_1 = REGISTRY.register("ysjtsj_1", Ysjtsj1Block::new);
		BAITIEKUANGSHI_0 = REGISTRY.register("baitiekuangshi_0", Baitiekuangshi0Block::new);
		BAITIEKUANGSHI_1 = REGISTRY.register("baitiekuangshi_1", Baitiekuangshi1Block::new);
		YSJSHUIJING_0 = REGISTRY.register("ysjshuijing_0", Ysjshuijing0Block::new);
		YSJSHUIJING_1 = REGISTRY.register("ysjshuijing_1", Ysjshuijing1Block::new);
		YSJSHUIJINGCU = REGISTRY.register("ysjshuijingcu", YsjshuijingcuBlock::new);
		CBTK = REGISTRY.register("cbtk", CbtkBlock::new);
		QIYU = REGISTRY.register("qiyu", QiyuBlock::new);
		XYDX = REGISTRY.register("xydx", XydxBlock::new);
		MLXZ = REGISTRY.register("mlxz", MlxzBlock::new);
		YSX = REGISTRY.register("ysx", YsxBlock::new);
		HYX = REGISTRY.register("hyx", HyxBlock::new);
		QXZHQ = REGISTRY.register("qxzhq", QxzhqBlock::new);
	}
	// Start of user code block custom blocks
	// End of user code block custom blocks
}