/*
*    MCreator note: This file will be REGENERATED on each build.
*/
package net.mcreator.ceshi.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.OnlyIn;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

import net.mcreator.ceshi.procedures.Yssp_sxProcedure;
import net.mcreator.ceshi.procedures.YsrzTypeProcedure;
import net.mcreator.ceshi.procedures.YdyhdltsxProcedure;
import net.mcreator.ceshi.procedures.FumoquanpinzhizhiProcedure;
import net.mcreator.ceshi.item.inventory.ZhangquanzhezhinangInventoryCapability;
import net.mcreator.ceshi.item.inventory.YishijiecunzheInventoryCapability;
import net.mcreator.ceshi.item.inventory.YibangrenzhinangInventoryCapability;
import net.mcreator.ceshi.item.inventory.MaoxianjiazhinangInventoryCapability;
import net.mcreator.ceshi.item.inventory.LiulangzhezhinangInventoryCapability;
import net.mcreator.ceshi.item.*;
import net.mcreator.ceshi.PrimogemcraftMod;

@EventBusSubscriber
public class PrimogemcraftModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(PrimogemcraftMod.MODID);
	public static final DeferredItem<Item> MINGWEI_YIQIEDEKAISHI;
	public static final DeferredItem<Item> YUANSHIKUANGSHI;
	public static final DeferredItem<Item> YUANSHI;
	public static final DeferredItem<Item> XIXIANGYUZHIYUAN;
	public static final DeferredItem<Item> JIJIUCHANZHIYUAN;
	public static final DeferredItem<Item> YISHIJIEYUANMUMUBAN;
	public static final DeferredItem<Item> CHUANGSHIJIEJING;
	public static final DeferredItem<Item> YISHIJIEMUGUN;
	public static final DeferredItem<Item> JIUCHANZHIYUANGAO;
	public static final DeferredItem<Item> JIUCHANZHIYUANKUAI;
	public static final DeferredItem<Item> JIUCHANZHIYUANXIAN;
	public static final DeferredItem<Item> YIYINHEDALETOU;
	public static final DeferredItem<Item> MMOLA_01;
	public static final DeferredItem<Item> QQIYUAN_JIN_GUANG_SPAWN_EGG;
	public static final DeferredItem<Item> Q_QYUANCHUZI_01_SPAWN_EGG;
	public static final DeferredItem<Item> QQ_QYUANCHULAN_01_SPAWN_EGG;
	public static final DeferredItem<Item> JINGUANGBAODI_01;
	public static final DeferredItem<Item> MOLADUI_02;
	public static final DeferredItem<Item> MOLAKUAI_01;
	public static final DeferredItem<Item> YIYISHIJIEMUBANLOUQI;
	public static final DeferredItem<Item> YIYISHIJIEYUANMUBANZHUAN;
	public static final DeferredItem<Item> YIYISHIJIEMUZHALAN;
	public static final DeferredItem<Item> YISHIJIEMUZHALAN;
	public static final DeferredItem<Item> QINLAODEZHEXUE;
	public static final DeferredItem<Item> HUANGJINDEZHEXUE;
	public static final DeferredItem<Item> FFANRONGDEZHEXUE;
	public static final DeferredItem<Item> SANYUEQIDIAOXIANG_01;
	public static final DeferredItem<Item> XIANGDANGANLAO;
	public static final DeferredItem<Item> JINGZHIMOLAKUAI;
	public static final DeferredItem<Item> LLIANJIAMOLAKUAI;
	public static final DeferredItem<Item> LIANJIAMOLAKUAIBANKUAI;
	public static final DeferredItem<Item> LLIANJIAMOLAKUIAITAIJIE;
	public static final DeferredItem<Item> LLIANJIAMOLAKUAIQIANG;
	public static final DeferredItem<Item> QIWUCHONGWANG;
	public static final DeferredItem<Item> SSANBAMIANTOU;
	public static final DeferredItem<Item> QQIWUZHANLIPINSHITI_SPAWN_EGG;
	public static final DeferredItem<Item> KKUIJIACESHI_HELMET;
	public static final DeferredItem<Item> KKUIJIACESHI_CHESTPLATE;
	public static final DeferredItem<Item> KKUIJIACESHI_LEGGINGS;
	public static final DeferredItem<Item> KKUIJIACESHI_BOOTS;
	public static final DeferredItem<Item> MMOLAGAO;
	public static final DeferredItem<Item> MMOLAFU;
	public static final DeferredItem<Item> MMOLACHAN;
	public static final DeferredItem<Item> MMOLAJIAN;
	public static final DeferredItem<Item> XIAOGUANZI;
	public static final DeferredItem<Item> DAGUANZI;
	public static final DeferredItem<Item> JINZHIMOLA;
	public static final DeferredItem<Item> WMOLADAI;
	public static final DeferredItem<Item> MMOLAPEIZIWUPIN;
	public static final DeferredItem<Item> XIAODAIMOLA;
	public static final DeferredItem<Item> SHILIANCHOU;
	public static final DeferredItem<Item> BAIGUANGGUODUSHENGWU_SPAWN_EGG;
	public static final DeferredItem<Item> WAWANXIANGWUCHANGTOU;
	public static final DeferredItem<Item> CEBUZHUNXIA;
	public static final DeferredItem<Item> XIANTIAOQIANG;
	public static final DeferredItem<Item> WUFENGJIAN;
	public static final DeferredItem<Item> GONGSIDEGUGUZHONG;
	public static final DeferredItem<Item> FULINJIAO;
	public static final DeferredItem<Item> LAJITONG;
	public static final DeferredItem<Item> LAJI;
	public static final DeferredItem<Item> LAJITONGZUNYAN;
	public static final DeferredItem<Item> ZHUANGMANLAJIDELAJITONG;
	public static final DeferredItem<Item> ZHONGKOUWEITIEDING;
	public static final DeferredItem<Item> HHAOKANDELAJI;
	public static final DeferredItem<Item> CESHIYONGWUPIN;
	public static final DeferredItem<Item> GANJINGLAJITONGXIANGZI;
	public static final DeferredItem<Item> MMOLAZHILAJITONG;
	public static final DeferredItem<Item> ZHZHENYINHEDALETOU;
	public static final DeferredItem<Item> ZIYOUSONGSHIKUANGSHI;
	public static final DeferredItem<Item> ZIZIYOUSONGSHISUIXIE;
	public static final DeferredItem<Item> ZZIYOUSONGSHIDUANPIAN;
	public static final DeferredItem<Item> ZZIYOUSONGSHIKUAI;
	public static final DeferredItem<Item> ZZIYOUSONGSHI;
	public static final DeferredItem<Item> ZIYOUSONGSHIKUAI;
	public static final DeferredItem<Item> BUFENGPING;
	public static final DeferredItem<Item> JIANLAOKUANGSHI;
	public static final DeferredItem<Item> JIANRANSUIXIE;
	public static final DeferredItem<Item> JIANLAODUANPIAN;
	public static final DeferredItem<Item> JIANLAOHUANGYU;
	public static final DeferredItem<Item> JIANLAOHUANGYUKUAI;
	public static final DeferredItem<Item> ZUISHENGSUIXIE;
	public static final DeferredItem<Item> ZUISHENGDUANPIAN;
	public static final DeferredItem<Item> ZUISHENGKUAI;
	public static final DeferredItem<Item> ZUISHENGZIJING;
	public static final DeferredItem<Item> ZUISHENGKUANGSHI;
	public static final DeferredItem<Item> ZUISNEGZIJINGKUAI;
	public static final DeferredItem<Item> MENGYING;
	public static final DeferredItem<Item> POSUIMENGYING;
	public static final DeferredItem<Item> SHENGZHANGKUANGSHI;
	public static final DeferredItem<Item> SHENGZHANGBIFEISUIXIE;
	public static final DeferredItem<Item> SHENGZHANGDUANPIAN;
	public static final DeferredItem<Item> SHENGZHANGKUAI;
	public static final DeferredItem<Item> SHENGZHANGBIFEI;
	public static final DeferredItem<Item> SHENGZHANGBIFEIDAKUAI;
	public static final DeferredItem<Item> CAOYUANHESHENGWU_SPAWN_EGG;
	public static final DeferredItem<Item> CAOYUANHE;
	public static final DeferredItem<Item> CAOYUANHEKUAI;
	public static final DeferredItem<Item> CAOYUANHEHUAMUBAN;
	public static final DeferredItem<Item> CAOYUANHEHUABUBAN_2;
	public static final DeferredItem<Item> CCAOYUANHEHUAMUBAN_3;
	public static final DeferredItem<Item> CESHI_MUCAIBAO_STAIRS;
	public static final DeferredItem<Item> CESHI_MUCAIBAO_SLAB;
	public static final DeferredItem<Item> CESHI_MUCAIBAO_FENCE;
	public static final DeferredItem<Item> CESHI_MUCAIBAO_FENCE_GATE;
	public static final DeferredItem<Item> CESHI_MUCAIBAO_PRESSURE_PLATE;
	public static final DeferredItem<Item> CESHI_MUCAIBAO_BUTTON;
	public static final DeferredItem<Item> CAOMULOUTI_21;
	public static final DeferredItem<Item> CAOMU_22;
	public static final DeferredItem<Item> CAOMO_23;
	public static final DeferredItem<Item> CAOMU_24;
	public static final DeferredItem<Item> CAOMU_25;
	public static final DeferredItem<Item> CAOMU_26;
	public static final DeferredItem<Item> CAOMU_31;
	public static final DeferredItem<Item> CAOMU_32;
	public static final DeferredItem<Item> CAOMU_33;
	public static final DeferredItem<Item> CAOMU_34;
	public static final DeferredItem<Item> CAOMU_35;
	public static final DeferredItem<Item> CAOMU_36;
	public static final DeferredItem<Item> PENGKELUODEJINGSHEN;
	public static final DeferredItem<Item> DIJINGQINJINGKUANGSHI;
	public static final DeferredItem<Item> DIJINGSUIXIE;
	public static final DeferredItem<Item> DIJINGDUANPIAN;
	public static final DeferredItem<Item> DIJINGKUAI;
	public static final DeferredItem<Item> DIIJINGQINGJING;
	public static final DeferredItem<Item> DIJINGQINGJINKUAI;
	public static final DeferredItem<Item> LIANJIAXIAJIEHEJINKUAI;
	public static final DeferredItem<Item> RANYUANMANAOKUANGSHI;
	public static final DeferredItem<Item> RANYUANSUIXIE;
	public static final DeferredItem<Item> RANYUANDUANPIAN;
	public static final DeferredItem<Item> RANYUANKUAI;
	public static final DeferredItem<Item> RRANYUANMANAO;
	public static final DeferredItem<Item> RANYUANKUAI_2;
	public static final DeferredItem<Item> MUTANKUAI;
	public static final DeferredItem<Item> XIJAIEYANGENGDI;
	public static final DeferredItem<Item> AIXUBINGYUKUANGSHI;
	public static final DeferredItem<Item> AIXUBINGYUSUIXIE;
	public static final DeferredItem<Item> AAIXUBINGYUDUANPIAN;
	public static final DeferredItem<Item> AIXUBINGYUKUAI;
	public static final DeferredItem<Item> AIXUBINGYU;
	public static final DeferredItem<Item> AIXUBINGYUFANGKU_I;
	public static final DeferredItem<Item> YUANSUJINGTI;
	public static final DeferredItem<Item> YUANSUJINGSHIKUAI;
	public static final DeferredItem<Item> SHANBIANZHICHEN;
	public static final DeferredItem<Item> XIAODENG_SPAWN_EGG;
	public static final DeferredItem<Item> XIAODENGWUPIN;
	public static final DeferredItem<Item> WEIZHIYEPIAN;
	public static final DeferredItem<Item> CESHIXIAODENGFASHEQI;
	public static final DeferredItem<Item> KONGYUEZHUFU;
	public static final DeferredItem<Item> SANYUEZHUFU;
	public static final DeferredItem<Item> LUANQIBAZAODEDAIMA;
	public static final DeferredItem<Item> YOUDIANQIQIAODEDAIMA;
	public static final DeferredItem<Item> ZHONGGUIZHONGJUDEDAIMA;
	public static final DeferredItem<Item> JINGQUEYOUYADAIMA;
	public static final DeferredItem<Item> MEIYOUZHUSHIDAIMA;
	public static final DeferredItem<Item> WUXIANDIGUIDEDAIMA;
	public static final DeferredItem<Item> FENLIEJINBI;
	public static final DeferredItem<Item> YUZHOUSUIPIAN;
	public static final DeferredItem<Item> SUIJI_1SHIJIAN;
	public static final DeferredItem<Item> CHUANGZAOXIAODENGFASHEQI;
	public static final DeferredItem<Item> CCHONGGAODAODEDEZANXU;
	public static final DeferredItem<Item> LIULANGZHEDEJINGYAN;
	public static final DeferredItem<Item> MAOXIANJIADEJINGYAN;
	public static final DeferredItem<Item> DAYINGXIONGDEJINGYAN;
	public static final DeferredItem<Item> YISHIJIEMUBAN_PLANKS;
	public static final DeferredItem<Item> YISHIJIEMUBAN_STAIRS;
	public static final DeferredItem<Item> YISHIJIEMUBAN_SLAB;
	public static final DeferredItem<Item> YISHIJIEMUBAN_FENCE;
	public static final DeferredItem<Item> YISHIJIEMUBAN_FENCE_GATE;
	public static final DeferredItem<Item> YISHIJIEMUBAN_PRESSURE_PLATE;
	public static final DeferredItem<Item> YISHIJIEMUBAN_BUTTON;
	public static final DeferredItem<Item> D_11;
	public static final DeferredItem<Item> D_12;
	public static final DeferredItem<Item> D_13;
	public static final DeferredItem<Item> D_14;
	public static final DeferredItem<Item> D_15;
	public static final DeferredItem<Item> D_16;
	public static final DeferredItem<Item> D_17;
	public static final DeferredItem<Item> JIANGLILIULANGZHEJINGYAN;
	public static final DeferredItem<Item> JIANGLIMAOXIANJIAJINGYAN;
	public static final DeferredItem<Item> JIANGLIDAYINXIONGJINGYAN;
	public static final DeferredItem<Item> TIAOGUOZHANG;
	public static final DeferredItem<Item> DISUIKUAI_1;
	public static final DeferredItem<Item> DISUISHUIJINGTI;
	public static final DeferredItem<Item> DISUI;
	public static final DeferredItem<Item> CANGSANGSHIZHUAN;
	public static final DeferredItem<Item> XIUTIEKUAI;
	public static final DeferredItem<Item> CSHIXIUTIEZHALAN;
	public static final DeferredItem<Item> XIUMU;
	public static final DeferredItem<Item> XIUXIUMULOUQI;
	public static final DeferredItem<Item> XIUMUZHALAN;
	public static final DeferredItem<Item> CANGSANGSHIZHUANLOUTI;
	public static final DeferredItem<Item> CANGSANGSHIZHUANTAIJIE;
	public static final DeferredItem<Item> CANGSANGSHIZHUANWEIQIANG;
	public static final DeferredItem<Item> YIYIMUGUOSHI;
	public static final DeferredItem<Item> WANSHINANG;
	public static final DeferredItem<Item> LAJITONGSUIPIAN;
	public static final DeferredItem<Item> LIULANGZHEZHINANG;
	public static final DeferredItem<Item> MAOXIANJIAZHINANG;
	public static final DeferredItem<Item> YIBANGRENZHINANG;
	public static final DeferredItem<Item> YINGJICUNCHUNANG;
	public static final DeferredItem<Item> SHIZUOYUANSHIKUAI;
	public static final DeferredItem<Item> FEIQIUPINGZHENG;
	public static final DeferredItem<Item> ZHAIQUAN;
	public static final DeferredItem<Item> TEZHIDIEYINGQI;
	public static final DeferredItem<Item> LAOSHI;
	public static final DeferredItem<Item> KAIFAQIANGZHI_01;
	public static final DeferredItem<Item> XIAOHEITA_SPAWN_EGG;
	public static final DeferredItem<Item> SHENSHENGHUABAN;
	public static final DeferredItem<Item> SHENBANYANYUANSHIKUANGSHI;
	public static final DeferredItem<Item> SHENBANJIANLAOHUANGYUKUANGSHI;
	public static final DeferredItem<Item> XINGHUI;
	public static final DeferredItem<Item> XINGCHEN;
	public static final DeferredItem<Item> JIANMUSHENGFAQI;
	public static final DeferredItem<Item> YUANSHIYUANPEI;
	public static final DeferredItem<Item> YUANSHIJIAN;
	public static final DeferredItem<Item> YUANSHIGAO;
	public static final DeferredItem<Item> YUANSHIFU;
	public static final DeferredItem<Item> YUANSHIQIAO;
	public static final DeferredItem<Item> YUANSHICHUTOU;
	public static final DeferredItem<Item> ZIZGAO;
	public static final DeferredItem<Item> ZIZAIFU;
	public static final DeferredItem<Item> JIANLAOKUAIWUPIN;
	public static final DeferredItem<Item> ZIZAIQIAO;
	public static final DeferredItem<Item> ZIZAICHU;
	public static final DeferredItem<Item> JLG;
	public static final DeferredItem<Item> JLF;
	public static final DeferredItem<Item> JLQ;
	public static final DeferredItem<Item> JLC;
	public static final DeferredItem<Item> ZSG;
	public static final DeferredItem<Item> ZSQ;
	public static final DeferredItem<Item> ZSF;
	public static final DeferredItem<Item> ZSC;
	public static final DeferredItem<Item> SZG;
	public static final DeferredItem<Item> SZF;
	public static final DeferredItem<Item> SZQ;
	public static final DeferredItem<Item> CAOYUANSUECI;
	public static final DeferredItem<Item> SZC;
	public static final DeferredItem<Item> DJG;
	public static final DeferredItem<Item> DJF;
	public static final DeferredItem<Item> DJQ;
	public static final DeferredItem<Item> DJC;
	public static final DeferredItem<Item> QGDYSJ;
	public static final DeferredItem<Item> RYG;
	public static final DeferredItem<Item> YSFC;
	public static final DeferredItem<Item> RYF;
	public static final DeferredItem<Item> RYQ;
	public static final DeferredItem<Item> RYC;
	public static final DeferredItem<Item> AXG;
	public static final DeferredItem<Item> YXAXG;
	public static final DeferredItem<Item> AXF;
	public static final DeferredItem<Item> AXQ;
	public static final DeferredItem<Item> AXC;
	public static final DeferredItem<Item> MMOLACHUTOU;
	public static final DeferredItem<Item> ZFG;
	public static final DeferredItem<Item> QWKWZJ;
	public static final DeferredItem<Item> SHQWYHDLT;
	public static final DeferredItem<Item> SHQWFNJ;
	public static final DeferredItem<Item> SHCBZX;
	public static final DeferredItem<Item> XINGJIDALETOU;
	public static final DeferredItem<Item> SHXJDLT;
	public static final DeferredItem<Item> QWTLDHY;
	public static final DeferredItem<Item> QWHDLZ;
	public static final DeferredItem<Item> JLBJ;
	public static final DeferredItem<Item> QWYBTZDYPJ;
	public static final DeferredItem<Item> QWXYZQ;
	public static final DeferredItem<Item> QWYMZJ;
	public static final DeferredItem<Item> QWFLYB;
	public static final DeferredItem<Item> QWXBZSQ;
	public static final DeferredItem<Item> MLXDML_01;
	public static final DeferredItem<Item> MLXDML_02;
	public static final DeferredItem<Item> MLXDML_03;
	public static final DeferredItem<Item> DBMLK;
	public static final DeferredItem<Item> QHMBML;
	public static final DeferredItem<Item> QHMBMLYS_01;
	public static final DeferredItem<Item> QHMBMLYS_02;
	public static final DeferredItem<Item> JLZA;
	public static final DeferredItem<Item> JLLIANG;
	public static final DeferredItem<Item> JLMO;
	public static final DeferredItem<Item> ZZJS;
	public static final DeferredItem<Item> JLZS;
	public static final DeferredItem<Item> YHJS;
	public static final DeferredItem<Item> ZHJS;
	public static final DeferredItem<Item> ZYJS;
	public static final DeferredItem<Item> RYJS;
	public static final DeferredItem<Item> LIJS;
	public static final DeferredItem<Item> ZZJLL;
	public static final DeferredItem<Item> JLJSL;
	public static final DeferredItem<Item> YHJSL;
	public static final DeferredItem<Item> ZHJSL;
	public static final DeferredItem<Item> ZYJSL;
	public static final DeferredItem<Item> RYJLL;
	public static final DeferredItem<Item> LAJSL;
	public static final DeferredItem<Item> ZZJSK;
	public static final DeferredItem<Item> JLJSK;
	public static final DeferredItem<Item> YHJSK;
	public static final DeferredItem<Item> ZHJSK;
	public static final DeferredItem<Item> ZYJSK;
	public static final DeferredItem<Item> RYJSK;
	public static final DeferredItem<Item> LAJSK;
	public static final DeferredItem<Item> DANGAOLIYUE;
	public static final DeferredItem<Item> YSJBFPK;
	public static final DeferredItem<Item> LJTG_01;
	public static final DeferredItem<Item> LJTG_02;
	public static final DeferredItem<Item> XZCFYXWZD;
	public static final DeferredItem<Item> CHUNMEIZHIPAO;
	public static final DeferredItem<Item> QWJZYJ;
	public static final DeferredItem<Item> XJHPYHFH;
	public static final DeferredItem<Item> CUNQUPINGZHENG;
	public static final DeferredItem<Item> JDYK;
	public static final DeferredItem<Item> BWDXJHPYHFH;
	public static final DeferredItem<Item> YISHIJIECUNZHE;
	public static final DeferredItem<Item> HQFENG;
	public static final DeferredItem<Item> HQYAN;
	public static final DeferredItem<Item> HQLEI;
	public static final DeferredItem<Item> HQCAO;
	public static final DeferredItem<Item> HQSHUI;
	public static final DeferredItem<Item> HQHUO;
	public static final DeferredItem<Item> HQBING;
	public static final DeferredItem<Item> MLJNB;
	public static final DeferredItem<Item> QWYZZM;
	public static final DeferredItem<Item> JIANSHIJINGBAN;
	public static final DeferredItem<Item> SHIWUTSSLM;
	public static final DeferredItem<Item> QIWUHEISENLINGGZ;
	public static final DeferredItem<Item> QWGGZFENLIE_A;
	public static final DeferredItem<Item> QWGGZFENLIE_B;
	public static final DeferredItem<Item> TESHUKUIJIA_01_HELMET;
	public static final DeferredItem<Item> GUZHONGLINGJIAN;
	public static final DeferredItem<Item> YDGGZ;
	public static final DeferredItem<Item> SHENMILIHE;
	public static final DeferredItem<Item> HUALIDUANZAO;
	public static final DeferredItem<Item> QWTCJLBPTBG;
	public static final DeferredItem<Item> QWLBTDGCL;
	public static final DeferredItem<Item> QUXGJIBING;
	public static final DeferredItem<Item> QWQCXXMX;
	public static final DeferredItem<Item> QWWXNTDMJ;
	public static final DeferredItem<Item> GZSMZ;
	public static final DeferredItem<Item> QWQSKXJXT;
	public static final DeferredItem<Item> QWSMCL;
	public static final DeferredItem<Item> SH_JWUPIN;
	public static final DeferredItem<Item> SJBCQ;
	public static final DeferredItem<Item> HHZD_0;
	public static final DeferredItem<Item> HHZD_1;
	public static final DeferredItem<Item> SHENMIWANOU;
	public static final DeferredItem<Item> HHZDBOO;
	public static final DeferredItem<Item> HHYINBAOQI;
	public static final DeferredItem<Item> YSJFR;
	public static final DeferredItem<Item> YSSP;
	public static final DeferredItem<Item> SUIJIWUPIN;
	public static final DeferredItem<Item> YUANSHIF;
	public static final DeferredItem<Item> YSJTSJ_0;
	public static final DeferredItem<Item> YSJTSJ_1;
	public static final DeferredItem<Item> MLLP;
	public static final DeferredItem<Item> MLLPWZ;
	public static final DeferredItem<Item> MLLPZS;
	public static final DeferredItem<Item> MLLPHJ;
	public static final DeferredItem<Item> ZSSP;
	public static final DeferredItem<Item> YHDLTYIDIE;
	public static final DeferredItem<Item> YDFMS;
	public static final DeferredItem<Item> YSRZ_0;
	public static final DeferredItem<Item> YSRQSP;
	public static final DeferredItem<Item> YSRZSPSX;
	public static final DeferredItem<Item> QYCX;
	public static final DeferredItem<Item> QYHX;
	public static final DeferredItem<Item> QYHXSHILIAN;
	public static final DeferredItem<Item> TIANKONGSP;
	public static final DeferredItem<Item> QYHX_0WUJIACHENG;
	public static final DeferredItem<Item> QWRHJ;
	public static final DeferredItem<Item> QWHCJ;
	public static final DeferredItem<Item> QWLHS;
	public static final DeferredItem<Item> QWLHA;
	public static final DeferredItem<Item> QWLHB;
	public static final DeferredItem<Item> QWKWZG;
	public static final DeferredItem<Item> QWCBZG;
	public static final DeferredItem<Item> QWYPZGS;
	public static final DeferredItem<Item> QWHYDLT;
	public static final DeferredItem<Item> QWZJXXMX;
	public static final DeferredItem<Item> QWFLB;
	public static final DeferredItem<Item> QWFLDYHDLB;
	public static final DeferredItem<Item> QWSBMB;
	public static final DeferredItem<Item> QWWXWCX;
	public static final DeferredItem<Item> QWYHNJ;
	public static final DeferredItem<Item> QWXGJB;
	public static final DeferredItem<Item> QWYHJB;
	public static final DeferredItem<Item> QWXGDBMT;
	public static final DeferredItem<Item> QWWSG;
	public static final DeferredItem<Item> QWTHHJ;
	public static final DeferredItem<Item> QWLHCC;
	public static final DeferredItem<Item> QWFJJ;
	public static final DeferredItem<Item> QWFJJWL;
	public static final DeferredItem<Item> QWXXGG;
	public static final DeferredItem<Item> QWWSZJ;
	public static final DeferredItem<Item> QWKWGL;
	public static final DeferredItem<Item> QWKWZT;
	public static final DeferredItem<Item> QWZCGS;
	public static final DeferredItem<Item> QWWCN;
	public static final DeferredItem<Item> QWWSGL;
	public static final DeferredItem<Item> QWTHHJIII;
	public static final DeferredItem<Item> QWWSX;
	public static final DeferredItem<Item> QWKWZW;
	public static final DeferredItem<Item> QWWSWCT;
	public static final DeferredItem<Item> QWYMWCT;
	public static final DeferredItem<Item> QWZCGL;
	public static final DeferredItem<Item> QWSMCD;
	public static final DeferredItem<Item> QWTLDGS;
	public static final DeferredItem<Item> QWCLGS;
	public static final DeferredItem<Item> QWWSHY;
	public static final DeferredItem<Item> QWJLBXYQ;
	public static final DeferredItem<Item> QWKZHY;
	public static final DeferredItem<Item> QWCLHY;
	public static final DeferredItem<Item> QWJLBHY;
	public static final DeferredItem<Item> QWYZNJ;
	public static final DeferredItem<Item> EXAMPLE;
	public static final DeferredItem<Item> WQZHG;
	public static final DeferredItem<Item> MYZJ;
	public static final DeferredItem<Item> XIWANGDEYITIAN_011;
	public static final DeferredItem<Item> BBUZAINIANQINGDEQINCEZHUANG_012;
	public static final DeferredItem<Item> SSHENHUDEZHUFU_013;
	public static final DeferredItem<Item> CCANGRUIMILINJIAN_014;
	public static final DeferredItem<Item> TAIKONGMANBUCHANGPIAN;
	public static final DeferredItem<Item> YYANZIYUELIANGCHANGPIAN;
	public static final DeferredItem<Item> TASHANGLVTUCHANGPIAN;
	public static final DeferredItem<Item> ZHAPIANDINGZHENGSHI;
	public static final DeferredItem<Item> GONGZHUXINGHUA;
	public static final DeferredItem<Item> FENGDANDAIBIAO;
	public static final DeferredItem<Item> CLLK;
	public static final DeferredItem<Item> ZFZR;
	public static final DeferredItem<Item> JHSB_0;
	public static final DeferredItem<Item> JHSB_1;
	public static final DeferredItem<Item> JHSB_2;
	public static final DeferredItem<Item> LMSJ;
	public static final DeferredItem<Item> DIJIAN;
	public static final DeferredItem<Item> XLLY;
	public static final DeferredItem<Item> FTYJ;
	public static final DeferredItem<Item> JSLYZH;
	public static final DeferredItem<Item> TKZR;
	public static final DeferredItem<Item> PYJL;
	public static final DeferredItem<Item> TCLWQCJQ;
	public static final DeferredItem<Item> TCLZHAIQUAN;
	public static final DeferredItem<Item> TCLLK;
	public static final DeferredItem<Item> HEIJIAN;
	public static final DeferredItem<Item> BAITIEKUANGSHI_0;
	public static final DeferredItem<Item> BAITIEKUANGSHI_1;
	public static final DeferredItem<Item> BAITIEKUANG;
	public static final DeferredItem<Item> YSJSHUIJING_0;
	public static final DeferredItem<Item> YSJSHUIJING_1;
	public static final DeferredItem<Item> YSJSJ;
	public static final DeferredItem<Item> YSJSHUIJINGCU;
	public static final DeferredItem<Item> S_WFENGRAOJIANGSHI_SPAWN_EGG;
	public static final DeferredItem<Item> QWSJGZQ;
	public static final DeferredItem<Item> QWSKLJ;
	public static final DeferredItem<Item> CBTK;
	public static final DeferredItem<Item> QWWZSW;
	public static final DeferredItem<Item> QIYU;
	public static final DeferredItem<Item> XINGQIONG;
	public static final DeferredItem<Item> XYZP;
	public static final DeferredItem<Item> XCKF;
	public static final DeferredItem<Item> XYDX;
	public static final DeferredItem<Item> QWXYDLT;
	public static final DeferredItem<Item> QWHYGZQ;
	public static final DeferredItem<Item> QWSKSJ;
	public static final DeferredItem<Item> SKJINB;
	public static final DeferredItem<Item> JDSBCF_0;
	public static final DeferredItem<Item> JDSBCF_1;
	public static final DeferredItem<Item> JDSBCF_2;
	public static final DeferredItem<Item> HYJSD;
	public static final DeferredItem<Item> MLXZ;
	public static final DeferredItem<Item> YSX;
	public static final DeferredItem<Item> HYX;
	public static final DeferredItem<Item> QWLZDLT;
	public static final DeferredItem<Item> QXZHQ;
	public static final DeferredItem<Item> QWSSS;
	public static final DeferredItem<Item> QWQXQWRHJ;
	public static final DeferredItem<Item> QWJCDM;
	public static final DeferredItem<Item> QWXYDSW;
	public static final DeferredItem<Item> QWXYDD;
	public static final DeferredItem<Item> SCMJ_HELMET;
	public static final DeferredItem<Item> QWSP;
	public static final DeferredItem<Item> QWCH;
	public static final DeferredItem<Item> QWSCQ;
	public static final DeferredItem<Item> QWMHS;
	public static final DeferredItem<Item> XINSHOUCQ;
	public static final DeferredItem<Item> HEIYINQ;
	public static final DeferredItem<Item> HMZZ;
	public static final DeferredItem<Item> XFCQ;
	public static final DeferredItem<Item> TCZDG;
	public static final DeferredItem<Item> JDZQ;
	public static final DeferredItem<Item> XLDJ;
	public static final DeferredItem<Item> QWTXZP;
	public static final DeferredItem<Item> QYSP;
	public static final DeferredItem<Item> EVENTITEM;
	public static final DeferredItem<Item> DIAMONDLOTTERY;
	public static final DeferredItem<Item> MYSTERYLOTTERY;
	static {
		MINGWEI_YIQIEDEKAISHI = REGISTRY.register("mingwei_yiqiedekaishi", BushizidanheItem::new);
		YUANSHIKUANGSHI = block(PrimogemcraftModBlocks.YUANSHIKUANGSHI);
		YUANSHI = REGISTRY.register("yuanshi", YuanshiItem::new);
		XIXIANGYUZHIYUAN = REGISTRY.register("xixiangyuzhiyuan", XixiangyuzhiyuanItem::new);
		JIJIUCHANZHIYUAN = REGISTRY.register("jijiuchanzhiyuan", JijiuchanzhiyuanItem::new);
		YISHIJIEYUANMUMUBAN = block(PrimogemcraftModBlocks.YISHIJIEYUANMUMUBAN);
		CHUANGSHIJIEJING = REGISTRY.register("chuangshijiejing", ChuangshijiejingItem::new);
		YISHIJIEMUGUN = REGISTRY.register("yishijiemugun", YishijiemugunItem::new);
		JIUCHANZHIYUANGAO = REGISTRY.register("jiuchanzhiyuangao", JiuchanzhiyuangaoItem::new);
		JIUCHANZHIYUANKUAI = block(PrimogemcraftModBlocks.JIUCHANZHIYUANKUAI);
		JIUCHANZHIYUANXIAN = REGISTRY.register("jiuchanzhiyuanxian", JiuchanzhiyuanxianItem::new);
		YIYINHEDALETOU = REGISTRY.register("yiyinhedaletou", YiyinhedaletouItem::new);
		MMOLA_01 = REGISTRY.register("mmola_01", Mmola01Item::new);
		QQIYUAN_JIN_GUANG_SPAWN_EGG = REGISTRY.register("qqiyuan_jin_guang_spawn_egg", () -> new DeferredSpawnEggItem(PrimogemcraftModEntities.QQIYUAN_JIN_GUANG, -1536, -2191, new Item.Properties()));
		Q_QYUANCHUZI_01_SPAWN_EGG = REGISTRY.register("q_qyuanchuzi_01_spawn_egg", () -> new DeferredSpawnEggItem(PrimogemcraftModEntities.Q_QYUANCHUZI_01, -3056653, -4118017, new Item.Properties()));
		QQ_QYUANCHULAN_01_SPAWN_EGG = REGISTRY.register("qq_qyuanchulan_01_spawn_egg", () -> new DeferredSpawnEggItem(PrimogemcraftModEntities.QQ_QYUANCHULAN_01, -10254081, -5449985, new Item.Properties()));
		JINGUANGBAODI_01 = REGISTRY.register("jinguangbaodi_01", Jinguangbaodi01Item::new);
		MOLADUI_02 = block(PrimogemcraftModBlocks.MOLADUI_02);
		MOLAKUAI_01 = block(PrimogemcraftModBlocks.MOLAKUAI_01);
		YIYISHIJIEMUBANLOUQI = block(PrimogemcraftModBlocks.YIYISHIJIEMUBANLOUQI);
		YIYISHIJIEYUANMUBANZHUAN = block(PrimogemcraftModBlocks.YIYISHIJIEYUANMUBANZHUAN);
		YIYISHIJIEMUZHALAN = block(PrimogemcraftModBlocks.YIYISHIJIEMUZHALAN);
		YISHIJIEMUZHALAN = block(PrimogemcraftModBlocks.YISHIJIEMUZHALAN);
		QINLAODEZHEXUE = REGISTRY.register("qinlaodezhexue", QinlaodezhexueItem::new);
		HUANGJINDEZHEXUE = REGISTRY.register("huangjindezhexue", HuangjindezhexueItem::new);
		FFANRONGDEZHEXUE = REGISTRY.register("ffanrongdezhexue", FfanrongdezhexueItem::new);
		SANYUEQIDIAOXIANG_01 = block(PrimogemcraftModBlocks.SANYUEQIDIAOXIANG_01);
		XIANGDANGANLAO = REGISTRY.register("xiangdanganlao", XiangdanganlaoItem::new);
		JINGZHIMOLAKUAI = block(PrimogemcraftModBlocks.JINGZHIMOLAKUAI);
		LLIANJIAMOLAKUAI = block(PrimogemcraftModBlocks.LLIANJIAMOLAKUAI);
		LIANJIAMOLAKUAIBANKUAI = block(PrimogemcraftModBlocks.LIANJIAMOLAKUAIBANKUAI);
		LLIANJIAMOLAKUIAITAIJIE = block(PrimogemcraftModBlocks.LLIANJIAMOLAKUIAITAIJIE);
		LLIANJIAMOLAKUAIQIANG = block(PrimogemcraftModBlocks.LLIANJIAMOLAKUAIQIANG);
		QIWUCHONGWANG = REGISTRY.register("qiwuchongwang", QiwuchongwangItem::new);
		SSANBAMIANTOU = REGISTRY.register("ssanbamiantou", SsanbamiantouItem::new);
		QQIWUZHANLIPINSHITI_SPAWN_EGG = REGISTRY.register("qqiwuzhanlipinshiti_spawn_egg", () -> new DeferredSpawnEggItem(PrimogemcraftModEntities.QQIWUZHANLIPINSHITI, -1, -1, new Item.Properties()));
		KKUIJIACESHI_HELMET = REGISTRY.register("kkuijiaceshi_helmet", KkuijiaceshiItem.Helmet::new);
		KKUIJIACESHI_CHESTPLATE = REGISTRY.register("kkuijiaceshi_chestplate", KkuijiaceshiItem.Chestplate::new);
		KKUIJIACESHI_LEGGINGS = REGISTRY.register("kkuijiaceshi_leggings", KkuijiaceshiItem.Leggings::new);
		KKUIJIACESHI_BOOTS = REGISTRY.register("kkuijiaceshi_boots", KkuijiaceshiItem.Boots::new);
		MMOLAGAO = REGISTRY.register("mmolagao", MmolagaoItem::new);
		MMOLAFU = REGISTRY.register("mmolafu", MmolafuItem::new);
		MMOLACHAN = REGISTRY.register("mmolachan", MmolachanItem::new);
		MMOLAJIAN = REGISTRY.register("mmolajian", MmolajianItem::new);
		XIAOGUANZI = block(PrimogemcraftModBlocks.XIAOGUANZI);
		DAGUANZI = block(PrimogemcraftModBlocks.DAGUANZI);
		JINZHIMOLA = REGISTRY.register("jinzhimola", JinzhimolaItem::new);
		WMOLADAI = REGISTRY.register("wmoladai", WmoladaiItem::new);
		MMOLAPEIZIWUPIN = REGISTRY.register("mmolapeiziwupin", MmolapeiziwupinItem::new);
		XIAODAIMOLA = REGISTRY.register("xiaodaimola", XiaodaimolaItem::new);
		SHILIANCHOU = REGISTRY.register("shilianchou", ShilianchouItem::new);
		BAIGUANGGUODUSHENGWU_SPAWN_EGG = REGISTRY.register("baiguangguodushengwu_spawn_egg", () -> new DeferredSpawnEggItem(PrimogemcraftModEntities.BAIGUANGGUODUSHENGWU, -1, -1, new Item.Properties()));
		WAWANXIANGWUCHANGTOU = REGISTRY.register("wawanxiangwuchangtou", WawanxiangwuchangtouItem::new);
		CEBUZHUNXIA = REGISTRY.register("cebuzhunxia", CebuzhunxiaItem::new);
		XIANTIAOQIANG = REGISTRY.register("xiantiaoqiang", XiantiaoqiangItem::new);
		WUFENGJIAN = REGISTRY.register("wufengjian", WufengjianItem::new);
		GONGSIDEGUGUZHONG = REGISTRY.register("gongsideguguzhong", GongsideguguzhongItem::new);
		FULINJIAO = REGISTRY.register("fulinjiao", FulinjiaoItem::new);
		LAJITONG = block(PrimogemcraftModBlocks.LAJITONG);
		LAJI = REGISTRY.register("laji", LajiItem::new);
		LAJITONGZUNYAN = REGISTRY.register("lajitongzunyan", LajitongzunyanItem::new);
		ZHUANGMANLAJIDELAJITONG = REGISTRY.register("zhuangmanlajidelajitong", ZhuangmanlajidelajitongItem::new);
		ZHONGKOUWEITIEDING = REGISTRY.register("zhongkouweitieding", ZhongkouweitiedingItem::new);
		HHAOKANDELAJI = REGISTRY.register("hhaokandelaji", HhaokandelajiItem::new);
		CESHIYONGWUPIN = REGISTRY.register("ceshiyongwupin", CeshiyongwupinItem::new);
		GANJINGLAJITONGXIANGZI = block(PrimogemcraftModBlocks.GANJINGLAJITONGXIANGZI);
		MMOLAZHILAJITONG = block(PrimogemcraftModBlocks.MMOLAZHILAJITONG);
		ZHZHENYINHEDALETOU = REGISTRY.register("zhzhenyinhedaletou", ZhzhenyinhedaletouItem::new);
		ZIYOUSONGSHIKUANGSHI = block(PrimogemcraftModBlocks.ZIYOUSONGSHIKUANGSHI);
		ZIZIYOUSONGSHISUIXIE = REGISTRY.register("ziziyousongshisuixie", ZiziyousongshisuixieItem::new);
		ZZIYOUSONGSHIDUANPIAN = REGISTRY.register("zziyousongshiduanpian", ZziyousongshiduanpianItem::new);
		ZZIYOUSONGSHIKUAI = REGISTRY.register("zziyousongshikuai", ZziyousongshikuaiItem::new);
		ZZIYOUSONGSHI = REGISTRY.register("zziyousongshi", ZziyousongshiItem::new);
		ZIYOUSONGSHIKUAI = block(PrimogemcraftModBlocks.ZIYOUSONGSHIKUAI);
		BUFENGPING = REGISTRY.register("bufengping", BufengpingItem::new);
		JIANLAOKUANGSHI = block(PrimogemcraftModBlocks.JIANLAOKUANGSHI);
		JIANRANSUIXIE = REGISTRY.register("jianransuixie", JianransuixieItem::new);
		JIANLAODUANPIAN = REGISTRY.register("jianlaoduanpian", JianlaoduanpianItem::new);
		JIANLAOHUANGYU = REGISTRY.register("jianlaohuangyu", JianlaohuangyuItem::new);
		JIANLAOHUANGYUKUAI = block(PrimogemcraftModBlocks.JIANLAOHUANGYUKUAI);
		ZUISHENGSUIXIE = REGISTRY.register("zuishengsuixie", ZuishengsuixieItem::new);
		ZUISHENGDUANPIAN = REGISTRY.register("zuishengduanpian", ZuishengduanpianItem::new);
		ZUISHENGKUAI = REGISTRY.register("zuishengkuai", ZuishengkuaiItem::new);
		ZUISHENGZIJING = REGISTRY.register("zuishengzijing", ZuishengzijingItem::new);
		ZUISHENGKUANGSHI = block(PrimogemcraftModBlocks.ZUISHENGKUANGSHI);
		ZUISNEGZIJINGKUAI = block(PrimogemcraftModBlocks.ZUISNEGZIJINGKUAI);
		MENGYING = REGISTRY.register("mengying", MengyingItem::new);
		POSUIMENGYING = REGISTRY.register("posuimengying", PosuimengyingItem::new);
		SHENGZHANGKUANGSHI = block(PrimogemcraftModBlocks.SHENGZHANGKUANGSHI);
		SHENGZHANGBIFEISUIXIE = REGISTRY.register("shengzhangbifeisuixie", ShengzhangbifeisuixieItem::new);
		SHENGZHANGDUANPIAN = REGISTRY.register("shengzhangduanpian", ShengzhangduanpianItem::new);
		SHENGZHANGKUAI = REGISTRY.register("shengzhangkuai", ShengzhangkuaiItem::new);
		SHENGZHANGBIFEI = REGISTRY.register("shengzhangbifei", ShengzhangbifeiItem::new);
		SHENGZHANGBIFEIDAKUAI = block(PrimogemcraftModBlocks.SHENGZHANGBIFEIDAKUAI);
		CAOYUANHESHENGWU_SPAWN_EGG = REGISTRY.register("caoyuanheshengwu_spawn_egg", () -> new DeferredSpawnEggItem(PrimogemcraftModEntities.CAOYUANHESHENGWU, -13369600, -3342490, new Item.Properties()));
		CAOYUANHE = REGISTRY.register("caoyuanhe", CaoyuanheItem::new);
		CAOYUANHEKUAI = block(PrimogemcraftModBlocks.CAOYUANHEKUAI);
		CAOYUANHEHUAMUBAN = block(PrimogemcraftModBlocks.CAOYUANHEHUAMUBAN);
		CAOYUANHEHUABUBAN_2 = block(PrimogemcraftModBlocks.CAOYUANHEHUABUBAN_2);
		CCAOYUANHEHUAMUBAN_3 = block(PrimogemcraftModBlocks.CCAOYUANHEHUAMUBAN_3);
		CESHI_MUCAIBAO_STAIRS = block(PrimogemcraftModBlocks.CESHI_MUCAIBAO_STAIRS);
		CESHI_MUCAIBAO_SLAB = block(PrimogemcraftModBlocks.CESHI_MUCAIBAO_SLAB);
		CESHI_MUCAIBAO_FENCE = block(PrimogemcraftModBlocks.CESHI_MUCAIBAO_FENCE);
		CESHI_MUCAIBAO_FENCE_GATE = block(PrimogemcraftModBlocks.CESHI_MUCAIBAO_FENCE_GATE);
		CESHI_MUCAIBAO_PRESSURE_PLATE = block(PrimogemcraftModBlocks.CESHI_MUCAIBAO_PRESSURE_PLATE);
		CESHI_MUCAIBAO_BUTTON = block(PrimogemcraftModBlocks.CESHI_MUCAIBAO_BUTTON);
		CAOMULOUTI_21 = block(PrimogemcraftModBlocks.CAOMULOUTI_21);
		CAOMU_22 = block(PrimogemcraftModBlocks.CAOMU_22);
		CAOMO_23 = block(PrimogemcraftModBlocks.CAOMO_23);
		CAOMU_24 = block(PrimogemcraftModBlocks.CAOMU_24);
		CAOMU_25 = block(PrimogemcraftModBlocks.CAOMU_25);
		CAOMU_26 = block(PrimogemcraftModBlocks.CAOMU_26);
		CAOMU_31 = block(PrimogemcraftModBlocks.CAOMU_31);
		CAOMU_32 = block(PrimogemcraftModBlocks.CAOMU_32);
		CAOMU_33 = block(PrimogemcraftModBlocks.CAOMU_33);
		CAOMU_34 = block(PrimogemcraftModBlocks.CAOMU_34);
		CAOMU_35 = block(PrimogemcraftModBlocks.CAOMU_35);
		CAOMU_36 = block(PrimogemcraftModBlocks.CAOMU_36);
		PENGKELUODEJINGSHEN = REGISTRY.register("pengkeluodejingshen", PengkeluodejingshenItem::new);
		DIJINGQINJINGKUANGSHI = block(PrimogemcraftModBlocks.DIJINGQINJINGKUANGSHI);
		DIJINGSUIXIE = REGISTRY.register("dijingsuixie", DijingsuixieItem::new);
		DIJINGDUANPIAN = REGISTRY.register("dijingduanpian", DijingduanpianItem::new);
		DIJINGKUAI = REGISTRY.register("dijingkuai", DijingkuaiItem::new);
		DIIJINGQINGJING = REGISTRY.register("diijingqingjing", DiijingqingjingItem::new);
		DIJINGQINGJINKUAI = block(PrimogemcraftModBlocks.DIJINGQINGJINKUAI);
		LIANJIAXIAJIEHEJINKUAI = block(PrimogemcraftModBlocks.LIANJIAXIAJIEHEJINKUAI);
		RANYUANMANAOKUANGSHI = block(PrimogemcraftModBlocks.RANYUANMANAOKUANGSHI);
		RANYUANSUIXIE = REGISTRY.register("ranyuansuixie", RanyuansuixieItem::new);
		RANYUANDUANPIAN = REGISTRY.register("ranyuanduanpian", RanyuanduanpianItem::new);
		RANYUANKUAI = REGISTRY.register("ranyuankuai", RanyuankuaiItem::new);
		RRANYUANMANAO = REGISTRY.register("rranyuanmanao", RranyuanmanaoItem::new);
		RANYUANKUAI_2 = block(PrimogemcraftModBlocks.RANYUANKUAI_2);
		MUTANKUAI = block(PrimogemcraftModBlocks.MUTANKUAI);
		XIJAIEYANGENGDI = block(PrimogemcraftModBlocks.XIJAIEYANGENGDI);
		AIXUBINGYUKUANGSHI = block(PrimogemcraftModBlocks.AIXUBINGYUKUANGSHI);
		AIXUBINGYUSUIXIE = REGISTRY.register("aixubingyusuixie", AixubingyusuixieItem::new);
		AAIXUBINGYUDUANPIAN = REGISTRY.register("aaixubingyuduanpian", AaixubingyuduanpianItem::new);
		AIXUBINGYUKUAI = REGISTRY.register("aixubingyukuai", AixubingyukuaiItem::new);
		AIXUBINGYU = REGISTRY.register("aixubingyu", AixubingyuItem::new);
		AIXUBINGYUFANGKU_I = block(PrimogemcraftModBlocks.AIXUBINGYUFANGKU_I);
		YUANSUJINGTI = REGISTRY.register("yuansujingti", YuansujingtiItem::new);
		YUANSUJINGSHIKUAI = block(PrimogemcraftModBlocks.YUANSUJINGSHIKUAI);
		SHANBIANZHICHEN = REGISTRY.register("shanbianzhichen", ShanbianzhichenItem::new);
		XIAODENG_SPAWN_EGG = REGISTRY.register("xiaodeng_spawn_egg", () -> new DeferredSpawnEggItem(PrimogemcraftModEntities.XIAODENG, -13312, -26368, new Item.Properties()));
		XIAODENGWUPIN = REGISTRY.register("xiaodengwupin", XiaodengwupinItem::new);
		WEIZHIYEPIAN = REGISTRY.register("weizhiyepian", WeizhiyepianItem::new);
		CESHIXIAODENGFASHEQI = block(PrimogemcraftModBlocks.CESHIXIAODENGFASHEQI);
		KONGYUEZHUFU = REGISTRY.register("kongyuezhufu", KongyuezhufuItem::new);
		SANYUEZHUFU = REGISTRY.register("sanyuezhufu", SanyuezhufuItem::new);
		LUANQIBAZAODEDAIMA = REGISTRY.register("luanqibazaodedaima", LuanqibazaodedaimaItem::new);
		YOUDIANQIQIAODEDAIMA = REGISTRY.register("youdianqiqiaodedaima", YoudianqiqiaodedaimaItem::new);
		ZHONGGUIZHONGJUDEDAIMA = REGISTRY.register("zhongguizhongjudedaima", ZhongguizhongjudedaimaItem::new);
		JINGQUEYOUYADAIMA = REGISTRY.register("jingqueyouyadaima", JingqueyouyadaimaItem::new);
		MEIYOUZHUSHIDAIMA = REGISTRY.register("meiyouzhushidaima", MeiyouzhushidaimaItem::new);
		WUXIANDIGUIDEDAIMA = REGISTRY.register("wuxiandiguidedaima", WuxiandiguidedaimaItem::new);
		FENLIEJINBI = REGISTRY.register("fenliejinbi", FenliejinbiItem::new);
		YUZHOUSUIPIAN = REGISTRY.register("yuzhousuipian", YuzhousuipianItem::new);
		SUIJI_1SHIJIAN = REGISTRY.register("suiji_1shijian", Suiji1shijianItem::new);
		CHUANGZAOXIAODENGFASHEQI = block(PrimogemcraftModBlocks.CHUANGZAOXIAODENGFASHEQI);
		CCHONGGAODAODEDEZANXU = REGISTRY.register("cchonggaodaodedezanxu", CchonggaodaodedezanxuItem::new);
		LIULANGZHEDEJINGYAN = REGISTRY.register("liulangzhedejingyan", LiulangzhedejingyanItem::new);
		MAOXIANJIADEJINGYAN = REGISTRY.register("maoxianjiadejingyan", MaoxianjiadejingyanItem::new);
		DAYINGXIONGDEJINGYAN = REGISTRY.register("dayingxiongdejingyan", DayingxiongdejingyanItem::new);
		YISHIJIEMUBAN_PLANKS = block(PrimogemcraftModBlocks.YISHIJIEMUBAN_PLANKS);
		YISHIJIEMUBAN_STAIRS = block(PrimogemcraftModBlocks.YISHIJIEMUBAN_STAIRS);
		YISHIJIEMUBAN_SLAB = block(PrimogemcraftModBlocks.YISHIJIEMUBAN_SLAB);
		YISHIJIEMUBAN_FENCE = block(PrimogemcraftModBlocks.YISHIJIEMUBAN_FENCE);
		YISHIJIEMUBAN_FENCE_GATE = block(PrimogemcraftModBlocks.YISHIJIEMUBAN_FENCE_GATE);
		YISHIJIEMUBAN_PRESSURE_PLATE = block(PrimogemcraftModBlocks.YISHIJIEMUBAN_PRESSURE_PLATE);
		YISHIJIEMUBAN_BUTTON = block(PrimogemcraftModBlocks.YISHIJIEMUBAN_BUTTON);
		D_11 = block(PrimogemcraftModBlocks.D_11);
		D_12 = block(PrimogemcraftModBlocks.D_12);
		D_13 = block(PrimogemcraftModBlocks.D_13);
		D_14 = block(PrimogemcraftModBlocks.D_14);
		D_15 = block(PrimogemcraftModBlocks.D_15);
		D_16 = block(PrimogemcraftModBlocks.D_16);
		D_17 = block(PrimogemcraftModBlocks.D_17);
		JIANGLILIULANGZHEJINGYAN = REGISTRY.register("jiangliliulangzhejingyan", JiangliliulangzhejingyanItem::new);
		JIANGLIMAOXIANJIAJINGYAN = REGISTRY.register("jianglimaoxianjiajingyan", JianglimaoxianjiajingyanItem::new);
		JIANGLIDAYINXIONGJINGYAN = REGISTRY.register("jianglidayinxiongjingyan", JianglidayinxiongjingyanItem::new);
		TIAOGUOZHANG = REGISTRY.register("tiaoguozhang", TiaoguozhangItem::new);
		DISUIKUAI_1 = block(PrimogemcraftModBlocks.DISUIKUAI_1);
		DISUISHUIJINGTI = block(PrimogemcraftModBlocks.DISUISHUIJINGTI);
		DISUI = REGISTRY.register("disui", DisuiItem::new);
		CANGSANGSHIZHUAN = block(PrimogemcraftModBlocks.CANGSANGSHIZHUAN);
		XIUTIEKUAI = block(PrimogemcraftModBlocks.XIUTIEKUAI);
		CSHIXIUTIEZHALAN = block(PrimogemcraftModBlocks.CSHIXIUTIEZHALAN);
		XIUMU = block(PrimogemcraftModBlocks.XIUMU);
		XIUXIUMULOUQI = block(PrimogemcraftModBlocks.XIUXIUMULOUQI);
		XIUMUZHALAN = block(PrimogemcraftModBlocks.XIUMUZHALAN);
		CANGSANGSHIZHUANLOUTI = block(PrimogemcraftModBlocks.CANGSANGSHIZHUANLOUTI);
		CANGSANGSHIZHUANTAIJIE = block(PrimogemcraftModBlocks.CANGSANGSHIZHUANTAIJIE);
		CANGSANGSHIZHUANWEIQIANG = block(PrimogemcraftModBlocks.CANGSANGSHIZHUANWEIQIANG);
		YIYIMUGUOSHI = REGISTRY.register("yiyimuguoshi", YiyimuguoshiItem::new);
		WANSHINANG = REGISTRY.register("wanshinang", WanshinangItem::new);
		LAJITONGSUIPIAN = REGISTRY.register("lajitongsuipian", LajitongsuipianItem::new);
		LIULANGZHEZHINANG = REGISTRY.register("liulangzhezhinang", LiulangzhezhinangItem::new);
		MAOXIANJIAZHINANG = REGISTRY.register("maoxianjiazhinang", MaoxianjiazhinangItem::new);
		YIBANGRENZHINANG = REGISTRY.register("yibangrenzhinang", ZhangquanzhezhinangItem::new);
		YINGJICUNCHUNANG = REGISTRY.register("yingjicunchunang", YibangrenzhinangItem::new);
		SHIZUOYUANSHIKUAI = block(PrimogemcraftModBlocks.SHIZUOYUANSHIKUAI);
		FEIQIUPINGZHENG = REGISTRY.register("feiqiupingzheng", FeiqiupingzhengItem::new);
		ZHAIQUAN = REGISTRY.register("zhaiquan", ZhaiquanItem::new);
		TEZHIDIEYINGQI = REGISTRY.register("tezhidieyingqi", TezhidieyingqiItem::new);
		LAOSHI = REGISTRY.register("laoshi", LaoshiItem::new);
		KAIFAQIANGZHI_01 = REGISTRY.register("kaifaqiangzhi_01", Kaifaqiangzhi01Item::new);
		XIAOHEITA_SPAWN_EGG = REGISTRY.register("xiaoheita_spawn_egg", () -> new DeferredSpawnEggItem(PrimogemcraftModEntities.XIAOHEITA, -7370515, -10414411, new Item.Properties()));
		SHENSHENGHUABAN = REGISTRY.register("shenshenghuaban", ShenshenghuabanItem::new);
		SHENBANYANYUANSHIKUANGSHI = block(PrimogemcraftModBlocks.SHENBANYANYUANSHIKUANGSHI);
		SHENBANJIANLAOHUANGYUKUANGSHI = block(PrimogemcraftModBlocks.SHENBANJIANLAOHUANGYUKUANGSHI);
		XINGHUI = REGISTRY.register("xinghui", XinghuiItem::new);
		XINGCHEN = REGISTRY.register("xingchen", XingchenItem::new);
		JIANMUSHENGFAQI = REGISTRY.register("jianmushengfaqi", JianmushengfaqiItem::new);
		YUANSHIYUANPEI = REGISTRY.register("yuanshiyuanpei", YuanshiyuanpeiItem::new);
		YUANSHIJIAN = REGISTRY.register("yuanshijian", YuanshijianItem::new);
		YUANSHIGAO = REGISTRY.register("yuanshigao", YuanshigaoItem::new);
		YUANSHIFU = REGISTRY.register("yuanshifu", YuanshifuItem::new);
		YUANSHIQIAO = REGISTRY.register("yuanshiqiao", YuanshiqiaoItem::new);
		YUANSHICHUTOU = REGISTRY.register("yuanshichutou", YuanshichutouItem::new);
		ZIZGAO = REGISTRY.register("zizgao", ZizgaoItem::new);
		ZIZAIFU = REGISTRY.register("zizaifu", ZizaifuItem::new);
		JIANLAOKUAIWUPIN = REGISTRY.register("jianlaokuaiwupin", JianlaokuaiwupinItem::new);
		ZIZAIQIAO = REGISTRY.register("zizaiqiao", ZizaiqiaoItem::new);
		ZIZAICHU = REGISTRY.register("zizaichu", ZizaichuItem::new);
		JLG = REGISTRY.register("jlg", JlgItem::new);
		JLF = REGISTRY.register("jlf", JlfItem::new);
		JLQ = REGISTRY.register("jlq", JlqItem::new);
		JLC = REGISTRY.register("jlc", JlcItem::new);
		ZSG = REGISTRY.register("zsg", ZsgItem::new);
		ZSQ = REGISTRY.register("zsq", ZsqItem::new);
		ZSF = REGISTRY.register("zsf", ZsfItem::new);
		ZSC = REGISTRY.register("zsc", ZscItem::new);
		SZG = REGISTRY.register("szg", SzgItem::new);
		SZF = REGISTRY.register("szf", SzfItem::new);
		SZQ = REGISTRY.register("szq", SzqItem::new);
		CAOYUANSUECI = block(PrimogemcraftModBlocks.CAOYUANSUECI);
		SZC = REGISTRY.register("szc", SzcItem::new);
		DJG = REGISTRY.register("djg", DjgItem::new);
		DJF = REGISTRY.register("djf", DjfItem::new);
		DJQ = REGISTRY.register("djq", DjqItem::new);
		DJC = REGISTRY.register("djc", DjcItem::new);
		QGDYSJ = REGISTRY.register("qgdysj", QgdysjItem::new);
		RYG = REGISTRY.register("ryg", RygItem::new);
		YSFC = REGISTRY.register("ysfc", YsfcItem::new);
		RYF = REGISTRY.register("ryf", RyfItem::new);
		RYQ = REGISTRY.register("ryq", RyqItem::new);
		RYC = REGISTRY.register("ryc", RycItem::new);
		AXG = REGISTRY.register("axg", AxgItem::new);
		YXAXG = REGISTRY.register("yxaxg", YxaxgItem::new);
		AXF = REGISTRY.register("axf", AxfItem::new);
		AXQ = REGISTRY.register("axq", AxqItem::new);
		AXC = REGISTRY.register("axc", AxcItem::new);
		MMOLACHUTOU = REGISTRY.register("mmolachutou", MolachutouItem::new);
		ZFG = REGISTRY.register("zfg", ZfgItem::new);
		QWKWZJ = REGISTRY.register("qwkwzj", QwkwzjItem::new);
		SHQWYHDLT = REGISTRY.register("shqwyhdlt", ShqwyhdltItem::new);
		SHQWFNJ = REGISTRY.register("shqwfnj", ShqwfnjItem::new);
		SHCBZX = REGISTRY.register("shcbzx", ShcbzxItem::new);
		XINGJIDALETOU = REGISTRY.register("xingjidaletou", XingjidaletouItem::new);
		SHXJDLT = REGISTRY.register("shxjdlt", ShxjdltItem::new);
		QWTLDHY = REGISTRY.register("qwtldhy", QwtldhyItem::new);
		QWHDLZ = REGISTRY.register("qwhdlz", QwhdlzItem::new);
		JLBJ = REGISTRY.register("jlbj", JlbjItem::new);
		QWYBTZDYPJ = REGISTRY.register("qwybtzdypj", QwybtzdypjItem::new);
		QWXYZQ = REGISTRY.register("qwxyzq", QwxyzqItem::new);
		QWYMZJ = REGISTRY.register("qwymzj", QwymzjItem::new);
		QWFLYB = REGISTRY.register("qwflyb", QwflybItem::new);
		QWXBZSQ = REGISTRY.register("qwxbzsq", QwxbzsqItem::new);
		MLXDML_01 = block(PrimogemcraftModBlocks.MLXDML_01);
		MLXDML_02 = block(PrimogemcraftModBlocks.MLXDML_02);
		MLXDML_03 = block(PrimogemcraftModBlocks.MLXDML_03);
		DBMLK = block(PrimogemcraftModBlocks.DBMLK);
		QHMBML = REGISTRY.register("qhmbml", QhmbmlItem::new);
		QHMBMLYS_01 = REGISTRY.register("qhmbmlys_01", Qhmbmlys01Item::new);
		QHMBMLYS_02 = REGISTRY.register("qhmbmlys_02", Qhmbmlys02Item::new);
		JLZA = REGISTRY.register("jlza", JlzaItem::new);
		JLLIANG = REGISTRY.register("jlliang", JlliangItem::new);
		JLMO = REGISTRY.register("jlmo", JlmoItem::new);
		ZZJS = REGISTRY.register("zzjs", ZzjsItem::new);
		JLZS = REGISTRY.register("jlzs", JlzsItem::new);
		YHJS = REGISTRY.register("yhjs", YhjsItem::new);
		ZHJS = REGISTRY.register("zhjs", ZhjsItem::new);
		ZYJS = REGISTRY.register("zyjs", ZyjsItem::new);
		RYJS = REGISTRY.register("ryjs", RyjsItem::new);
		LIJS = REGISTRY.register("lijs", LijsItem::new);
		ZZJLL = REGISTRY.register("zzjll", ZzjllItem::new);
		JLJSL = REGISTRY.register("jljsl", JljslItem::new);
		YHJSL = REGISTRY.register("yhjsl", YhjslItem::new);
		ZHJSL = REGISTRY.register("zhjsl", ZhjslItem::new);
		ZYJSL = REGISTRY.register("zyjsl", ZyjslItem::new);
		RYJLL = REGISTRY.register("ryjll", RyjllItem::new);
		LAJSL = REGISTRY.register("lajsl", LajslItem::new);
		ZZJSK = block(PrimogemcraftModBlocks.ZZJSK);
		JLJSK = block(PrimogemcraftModBlocks.JLJSK);
		YHJSK = block(PrimogemcraftModBlocks.YHJSK);
		ZHJSK = block(PrimogemcraftModBlocks.ZHJSK);
		ZYJSK = block(PrimogemcraftModBlocks.ZYJSK);
		RYJSK = block(PrimogemcraftModBlocks.RYJSK);
		LAJSK = block(PrimogemcraftModBlocks.LAJSK);
		DANGAOLIYUE = block(PrimogemcraftModBlocks.DANGAOLIYUE);
		YSJBFPK = REGISTRY.register("ysjbfpk", YsjbfpkItem::new);
		LJTG_01 = REGISTRY.register("ljtg_01", Ljtg01Item::new);
		LJTG_02 = REGISTRY.register("ljtg_02", Ljtg02Item::new);
		XZCFYXWZD = REGISTRY.register("xzcfyxwzd", XzcfyxwzdItem::new);
		CHUNMEIZHIPAO = REGISTRY.register("chunmeizhipao", ChunmeizhipaoItem::new);
		QWJZYJ = REGISTRY.register("qwjzyj", QwjzyjItem::new);
		XJHPYHFH = block(PrimogemcraftModBlocks.XJHPYHFH);
		CUNQUPINGZHENG = REGISTRY.register("cunqupingzheng", CunqupingzhengItem::new);
		JDYK = block(PrimogemcraftModBlocks.JDYK);
		BWDXJHPYHFH = block(PrimogemcraftModBlocks.BWDXJHPYHFH);
		YISHIJIECUNZHE = REGISTRY.register("yishijiecunzhe", YishijiecunzheItem::new);
		HQFENG = REGISTRY.register("hqfeng", HqfengItem::new);
		HQYAN = REGISTRY.register("hqyan", HqyanItem::new);
		HQLEI = REGISTRY.register("hqlei", HqleiItem::new);
		HQCAO = REGISTRY.register("hqcao", HqcaoItem::new);
		HQSHUI = REGISTRY.register("hqshui", HqshuiItem::new);
		HQHUO = REGISTRY.register("hqhuo", HqhuoItem::new);
		HQBING = REGISTRY.register("hqbing", HqbingItem::new);
		MLJNB = REGISTRY.register("mljnb", MljnbItem::new);
		QWYZZM = REGISTRY.register("qwyzzm", QwyzzmItem::new);
		JIANSHIJINGBAN = block(PrimogemcraftModBlocks.JIANSHIJINGBAN);
		SHIWUTSSLM = REGISTRY.register("shiwutsslm", ShiwutsslmItem::new);
		QIWUHEISENLINGGZ = REGISTRY.register("qiwuheisenlinggz", QiwuheisenlinggzItem::new);
		QWGGZFENLIE_A = REGISTRY.register("qwggzfenlie_a", QwggzfenlieAItem::new);
		QWGGZFENLIE_B = REGISTRY.register("qwggzfenlie_b", QwggzfenlieBItem::new);
		TESHUKUIJIA_01_HELMET = REGISTRY.register("teshukuijia_01_helmet", Teshukuijia01Item.Helmet::new);
		GUZHONGLINGJIAN = REGISTRY.register("guzhonglingjian", GuzhonglingjianItem::new);
		YDGGZ = REGISTRY.register("ydggz", YdggzItem::new);
		SHENMILIHE = REGISTRY.register("shenmilihe", ShenmiliheItem::new);
		HUALIDUANZAO = block(PrimogemcraftModBlocks.HUALIDUANZAO);
		QWTCJLBPTBG = REGISTRY.register("qwtcjlbptbg", QwtcjlbptbgItem::new);
		QWLBTDGCL = REGISTRY.register("qwlbtdgcl", QwlbtdgclItem::new);
		QUXGJIBING = REGISTRY.register("quxgjibing", QuxgjibingItem::new);
		QWQCXXMX = REGISTRY.register("qwqcxxmx", QwqcxxmxItem::new);
		QWWXNTDMJ = REGISTRY.register("qwwxntdmj", QwwxntdmjItem::new);
		GZSMZ = REGISTRY.register("gzsmz", GzsmzItem::new);
		QWQSKXJXT = REGISTRY.register("qwqskxjxt", QwqskxjxtItem::new);
		QWSMCL = REGISTRY.register("qwsmcl", QwsmclItem::new);
		SH_JWUPIN = REGISTRY.register("sh_jwupin", SHJwupinItem::new);
		SJBCQ = REGISTRY.register("sjbcq", SjbcqItem::new);
		HHZD_0 = block(PrimogemcraftModBlocks.HHZD_0);
		HHZD_1 = block(PrimogemcraftModBlocks.HHZD_1);
		SHENMIWANOU = block(PrimogemcraftModBlocks.SHENMIWANOU);
		HHZDBOO = block(PrimogemcraftModBlocks.HHZDBOO);
		HHYINBAOQI = block(PrimogemcraftModBlocks.HHYINBAOQI);
		YSJFR = REGISTRY.register("ysjfr", YsjfrItem::new);
		YSSP = REGISTRY.register("yssp", YsspItem::new);
		SUIJIWUPIN = REGISTRY.register("suijiwupin", SuijiwupinItem::new);
		YUANSHIF = REGISTRY.register("yuanshif", YuanshifItem::new);
		YSJTSJ_0 = block(PrimogemcraftModBlocks.YSJTSJ_0);
		YSJTSJ_1 = block(PrimogemcraftModBlocks.YSJTSJ_1);
		MLLP = REGISTRY.register("mllp", MllpItem::new);
		MLLPWZ = REGISTRY.register("mllpwz", MllpwzItem::new);
		MLLPZS = REGISTRY.register("mllpzs", MllpzsItem::new);
		MLLPHJ = REGISTRY.register("mllphj", MllphjItem::new);
		ZSSP = REGISTRY.register("zssp", ZsspItem::new);
		YHDLTYIDIE = REGISTRY.register("yhdltyidie", YhdltyidieItem::new);
		YDFMS = REGISTRY.register("ydfms", YdfmsItem::new);
		YSRZ_0 = REGISTRY.register("ysrz_0", Ysrz0Item::new);
		YSRQSP = REGISTRY.register("ysrqsp", YsrqspItem::new);
		YSRZSPSX = REGISTRY.register("ysrzspsx", YsrzspsxItem::new);
		QYCX = REGISTRY.register("qycx", QycxItem::new);
		QYHX = REGISTRY.register("qyhx", QyhxItem::new);
		QYHXSHILIAN = REGISTRY.register("qyhxshilian", QyhxshilianItem::new);
		TIANKONGSP = REGISTRY.register("tiankongsp", TiankongspItem::new);
		QYHX_0WUJIACHENG = REGISTRY.register("qyhx_0wujiacheng", Qyhx0wujiachengItem::new);
		QWRHJ = REGISTRY.register("qwrhj", QwrhjItem::new);
		QWHCJ = REGISTRY.register("qwhcj", QwhcjItem::new);
		QWLHS = REGISTRY.register("qwlhs", QwlhsItem::new);
		QWLHA = REGISTRY.register("qwlha", QwlhaItem::new);
		QWLHB = REGISTRY.register("qwlhb", QwlhbItem::new);
		QWKWZG = REGISTRY.register("qwkwzg", QwkwzgItem::new);
		QWCBZG = REGISTRY.register("qwcbzg", QwcbzgItem::new);
		QWYPZGS = REGISTRY.register("qwypzgs", QwypzgsItem::new);
		QWHYDLT = REGISTRY.register("qwhydlt", QwhydltItem::new);
		QWZJXXMX = REGISTRY.register("qwzjxxmx", QwzjxxmxItem::new);
		QWFLB = REGISTRY.register("qwflb", QwflbItem::new);
		QWFLDYHDLB = REGISTRY.register("qwfldyhdlb", QwfldyhdlbItem::new);
		QWSBMB = REGISTRY.register("qwsbmb", QwsbmbItem::new);
		QWWXWCX = REGISTRY.register("qwwxwcx", QwwxwcxItem::new);
		QWYHNJ = REGISTRY.register("qwyhnj", QwyhnjItem::new);
		QWXGJB = REGISTRY.register("qwxgjb", QwxgjbItem::new);
		QWYHJB = REGISTRY.register("qwyhjb", QwyhjbItem::new);
		QWXGDBMT = REGISTRY.register("qwxgdbmt", QwxgdbmtItem::new);
		QWWSG = REGISTRY.register("qwwsg", QwwsgItem::new);
		QWTHHJ = REGISTRY.register("qwthhj", QwthhjItem::new);
		QWLHCC = REGISTRY.register("qwlhcc", QwlhccItem::new);
		QWFJJ = REGISTRY.register("qwfjj", QwfjjItem::new);
		QWFJJWL = REGISTRY.register("qwfjjwl", QwfjjwlItem::new);
		QWXXGG = REGISTRY.register("qwxxgg", QwxxggItem::new);
		QWWSZJ = REGISTRY.register("qwwszj", QwwszjItem::new);
		QWKWGL = REGISTRY.register("qwkwgl", QwkwglItem::new);
		QWKWZT = REGISTRY.register("qwkwzt", QwkwztItem::new);
		QWZCGS = REGISTRY.register("qwzcgs", QwzcgsItem::new);
		QWWCN = REGISTRY.register("qwwcn", QwwcnItem::new);
		QWWSGL = REGISTRY.register("qwwsgl", QwwsglItem::new);
		QWTHHJIII = REGISTRY.register("qwthhjiii", QwthhjiiiItem::new);
		QWWSX = REGISTRY.register("qwwsx", QwwsxItem::new);
		QWKWZW = REGISTRY.register("qwkwzw", QwkwzwItem::new);
		QWWSWCT = REGISTRY.register("qwwswct", QwwswctItem::new);
		QWYMWCT = REGISTRY.register("qwymwct", QwymwctItem::new);
		QWZCGL = REGISTRY.register("qwzcgl", QwzcglItem::new);
		QWSMCD = REGISTRY.register("qwsmcd", QwsmcdItem::new);
		QWTLDGS = REGISTRY.register("qwtldgs", QwtldgsItem::new);
		QWCLGS = REGISTRY.register("qwclgs", QwclgsItem::new);
		QWWSHY = REGISTRY.register("qwwshy", QwwshyItem::new);
		QWJLBXYQ = REGISTRY.register("qwjlbxyq", QwjlbxyqItem::new);
		QWKZHY = REGISTRY.register("qwkzhy", QwkzhyItem::new);
		QWCLHY = REGISTRY.register("qwclhy", QwclhyItem::new);
		QWJLBHY = REGISTRY.register("qwjlbhy", QwjlbhyItem::new);
		QWYZNJ = REGISTRY.register("qwyznj", QwyznjItem::new);
		EXAMPLE = REGISTRY.register("example", ExampleItem::new);
		WQZHG = REGISTRY.register("wqzhg", WqzhgItem::new);
		MYZJ = REGISTRY.register("myzj", MyzjItem::new);
		XIWANGDEYITIAN_011 = REGISTRY.register("xiwangdeyitian_011", Xiwangdeyitian011Item::new);
		BBUZAINIANQINGDEQINCEZHUANG_012 = REGISTRY.register("bbuzainianqingdeqincezhuang_012", Bbuzainianqingdeqincezhuang012Item::new);
		SSHENHUDEZHUFU_013 = REGISTRY.register("sshenhudezhufu_013", Sshenhudezhufu013Item::new);
		CCANGRUIMILINJIAN_014 = REGISTRY.register("ccangruimilinjian_014", Ccangruimilinjian014Item::new);
		TAIKONGMANBUCHANGPIAN = REGISTRY.register("taikongmanbuchangpian", TaikongmanbuchangpianItem::new);
		YYANZIYUELIANGCHANGPIAN = REGISTRY.register("yyanziyueliangchangpian", YyanziyueliangchangpianItem::new);
		TASHANGLVTUCHANGPIAN = REGISTRY.register("tashanglvtuchangpian", TashanglvtuchangpianItem::new);
		ZHAPIANDINGZHENGSHI = REGISTRY.register("zhapiandingzhengshi", ZhapiandingzhengshiItem::new);
		GONGZHUXINGHUA = REGISTRY.register("gongzhuxinghua", GongzhuxinghuaItem::new);
		FENGDANDAIBIAO = REGISTRY.register("fengdandaibiao", FengdandaibiaoItem::new);
		CLLK = REGISTRY.register("cllk", CllkItem::new);
		ZFZR = REGISTRY.register("zfzr", ZfzrItem::new);
		JHSB_0 = REGISTRY.register("jhsb_0", Jhsb0Item::new);
		JHSB_1 = REGISTRY.register("jhsb_1", Jhsb1Item::new);
		JHSB_2 = REGISTRY.register("jhsb_2", Jhsb2Item::new);
		LMSJ = REGISTRY.register("lmsj", LmsjItem::new);
		DIJIAN = REGISTRY.register("dijian", DijianItem::new);
		XLLY = REGISTRY.register("xlly", XllyItem::new);
		FTYJ = REGISTRY.register("ftyj", FtyjItem::new);
		JSLYZH = REGISTRY.register("jslyzh", JslyzhItem::new);
		TKZR = REGISTRY.register("tkzr", TkzrItem::new);
		PYJL = REGISTRY.register("pyjl", PyjlItem::new);
		TCLWQCJQ = REGISTRY.register("tclwqcjq", TclwqcjqItem::new);
		TCLZHAIQUAN = REGISTRY.register("tclzhaiquan", TclzhaiquanItem::new);
		TCLLK = REGISTRY.register("tcllk", TcllkItem::new);
		HEIJIAN = REGISTRY.register("heijian", HeijianItem::new);
		BAITIEKUANGSHI_0 = block(PrimogemcraftModBlocks.BAITIEKUANGSHI_0);
		BAITIEKUANGSHI_1 = block(PrimogemcraftModBlocks.BAITIEKUANGSHI_1);
		BAITIEKUANG = REGISTRY.register("baitiekuang", BaitiekuangItem::new);
		YSJSHUIJING_0 = block(PrimogemcraftModBlocks.YSJSHUIJING_0);
		YSJSHUIJING_1 = block(PrimogemcraftModBlocks.YSJSHUIJING_1);
		YSJSJ = REGISTRY.register("ysjsj", YsjsjItem::new);
		YSJSHUIJINGCU = block(PrimogemcraftModBlocks.YSJSHUIJINGCU);
		S_WFENGRAOJIANGSHI_SPAWN_EGG = REGISTRY.register("s_wfengraojiangshi_spawn_egg", () -> new DeferredSpawnEggItem(PrimogemcraftModEntities.S_WFENGRAOJIANGSHI, -16751053, -13312, new Item.Properties()));
		QWSJGZQ = REGISTRY.register("qwsjgzq", QwsjgzqItem::new);
		QWSKLJ = REGISTRY.register("qwsklj", QwskljItem::new);
		CBTK = block(PrimogemcraftModBlocks.CBTK);
		QWWZSW = REGISTRY.register("qwwzsw", QwwzswItem::new);
		QIYU = block(PrimogemcraftModBlocks.QIYU);
		XINGQIONG = REGISTRY.register("xingqiong", XingqiongItem::new);
		XYZP = REGISTRY.register("xyzp", XyzpItem::new);
		XCKF = REGISTRY.register("xckf", XckfItem::new);
		XYDX = block(PrimogemcraftModBlocks.XYDX);
		QWXYDLT = REGISTRY.register("qwxydlt", QwxydltItem::new);
		QWHYGZQ = REGISTRY.register("qwhygzq", QwhygzqItem::new);
		QWSKSJ = REGISTRY.register("qwsksj", QwsksjItem::new);
		SKJINB = REGISTRY.register("skjinb", SkjinbItem::new);
		JDSBCF_0 = REGISTRY.register("jdsbcf_0", Jdsbcf0Item::new);
		JDSBCF_1 = REGISTRY.register("jdsbcf_1", Jdsbcf1Item::new);
		JDSBCF_2 = REGISTRY.register("jdsbcf_2", Jdsbcf2Item::new);
		HYJSD = REGISTRY.register("hyjsd", HyjsdItem::new);
		MLXZ = block(PrimogemcraftModBlocks.MLXZ);
		YSX = block(PrimogemcraftModBlocks.YSX);
		HYX = block(PrimogemcraftModBlocks.HYX);
		QWLZDLT = REGISTRY.register("qwlzdlt", QwlzdltItem::new);
		QXZHQ = block(PrimogemcraftModBlocks.QXZHQ);
		QWSSS = REGISTRY.register("qwsss", QwsssItem::new);
		QWQXQWRHJ = REGISTRY.register("qwqxqwrhj", QwqxqwrhjItem::new);
		QWJCDM = REGISTRY.register("qwjcdm", QwjcdmItem::new);
		QWXYDSW = REGISTRY.register("qwxydsw", QwxydswItem::new);
		QWXYDD = REGISTRY.register("qwxydd", QwxyddItem::new);
		SCMJ_HELMET = REGISTRY.register("scmj_helmet", ScmjItem.Helmet::new);
		QWSP = REGISTRY.register("qwsp", QwspItem::new);
		QWCH = REGISTRY.register("qwch", QwchItem::new);
		QWSCQ = REGISTRY.register("qwscq", QwscqItem::new);
		QWMHS = REGISTRY.register("qwmhs", QwmhsItem::new);
		XINSHOUCQ = REGISTRY.register("xinshoucq", XinshoucqItem::new);
		HEIYINQ = REGISTRY.register("heiyinq", HeiyinqItem::new);
		HMZZ = REGISTRY.register("hmzz", HmzzItem::new);
		XFCQ = REGISTRY.register("xfcq", XfcqItem::new);
		TCZDG = REGISTRY.register("tczdg", TczdgItem::new);
		JDZQ = REGISTRY.register("jdzq", JdzqItem::new);
		XLDJ = REGISTRY.register("xldj", XldjItem::new);
		QWTXZP = REGISTRY.register("qwtxzp", QwtxzpItem::new);
		QYSP = REGISTRY.register("qysp", QyspItem::new);
		EVENTITEM = REGISTRY.register("eventitem", EventitemItem::new);
		DIAMONDLOTTERY = REGISTRY.register("diamondlottery", DiamondlotteryItem::new);
		MYSTERYLOTTERY = REGISTRY.register("mysterylottery", MysterylotteryItem::new);
	}
	// Start of user code block custom items
	public static final DeferredItem<Item> HPY = REGISTRY.register("hpy", Hpy::new);

	// End of user code block custom items
	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new LiulangzhezhinangInventoryCapability(stack), LIULANGZHEZHINANG.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new MaoxianjiazhinangInventoryCapability(stack), MAOXIANJIAZHINANG.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new ZhangquanzhezhinangInventoryCapability(stack), YIBANGRENZHINANG.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new YibangrenzhinangInventoryCapability(stack), YINGJICUNCHUNANG.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new YishijiecunzheInventoryCapability(stack), YISHIJIECUNZHE.get());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}

	@EventBusSubscriber(Dist.CLIENT)
	public static class ItemsClientSideHandler {
		@SubscribeEvent
		@OnlyIn(Dist.CLIENT)
		public static void clientLoad(FMLClientSetupEvent event) {
			event.enqueueWork(() -> {
				ItemProperties.register(MMOLA_01.get(), ResourceLocation.parse("primogemcraft:mmola_01_shuliang"),
						(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) Yssp_sxProcedure.execute(entity != null ? entity.level() : clientWorld, itemStackToRender));
				ItemProperties.register(LJTG_01.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
				ItemProperties.register(LJTG_02.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
				ItemProperties.register(XZCFYXWZD.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
				ItemProperties.register(SJBCQ.get(), ResourceLocation.parse("primogemcraft:sjbcq_pinzhi"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) FumoquanpinzhizhiProcedure.execute(itemStackToRender));
				ItemProperties.register(YSSP.get(), ResourceLocation.parse("primogemcraft:yssp_shuliang"),
						(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) Yssp_sxProcedure.execute(entity != null ? entity.level() : clientWorld, itemStackToRender));
				ItemProperties.register(ZSSP.get(), ResourceLocation.parse("primogemcraft:zssp_shuliang"),
						(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) Yssp_sxProcedure.execute(entity != null ? entity.level() : clientWorld, itemStackToRender));
				ItemProperties.register(YHDLTYIDIE.get(), ResourceLocation.parse("primogemcraft:yhdltyidie_shuliang"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) YdyhdltsxProcedure.execute(itemStackToRender));
				ItemProperties.register(YSRZ_0.get(), ResourceLocation.parse("primogemcraft:ysrz_0_type"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) YsrzTypeProcedure.execute(itemStackToRender));
				ItemProperties.register(YSRQSP.get(), ResourceLocation.parse("primogemcraft:ysrqsp_shu"),
						(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) Yssp_sxProcedure.execute(entity != null ? entity.level() : clientWorld, itemStackToRender));
			});
		}
	}
}