modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="primogemcraft"
version="2435"
displayName="原石工艺"
displayURL="https://www.mcmod.cn/class/10429.html"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Pepper某人, hackerm大神, MCreator"
description="这是一个无厘头的娱乐性mod，包含一些米游物品和梗"

# Start of user code block mod configuration
[[mixins]]
config = "pgc.mixins.json"
# End of user code block mod configuration

[[dependencies.primogemcraft]]
modId="neoforge"
type="required"
versionRange="[20.6.119,)"
ordering="AFTER"
side="BOTH"

[[dependencies.primogemcraft]]
modId="minecraft"
type="required"
versionRange="[1.20.6]"
ordering="AFTER"
side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration
